"""SQLite→PostgreSQL statement translation (spec §11, Sprint 10/11).

``PostgresDatabase._translate`` rewrites SQLite-style ``?`` placeholders to
psycopg ``%s`` and ``AUTOINCREMENT`` to identity columns. These tests pin
the translation for the statements the Sprint 11 Postgres adapters rely on
(``FOR UPDATE SKIP LOCKED`` claims, idempotency partial unique indexes),
without requiring a live PostgreSQL server.
"""

from voodoo.storage.database.postgres import _translate

CLAIM_SQL = """
UPDATE tasks SET
    status = 'running',
    attempts = attempts + 1,
    locked_by = ?, locked_at = ?, lease_until = ?
WHERE id = (
    SELECT id FROM tasks
    WHERE status IN ('pending', 'retrying') AND available_at <= ?
    ORDER BY priority DESC, available_at ASC, id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, type, payload, status
"""


def test_skip_locked_passes_through_unchanged() -> None:
    """The PG claim variant keeps FOR UPDATE SKIP LOCKED verbatim (Sprint 11)."""
    out = _translate(CLAIM_SQL)
    assert "FOR UPDATE SKIP LOCKED" in out
    # Only the ? placeholders changed; everything else is textually identical.
    assert out.count("%s") == 4
    assert "?" not in out
    assert "RETURNING id, type, payload, status" in out


def test_auto_increment_becomes_identity() -> None:
    sql = "CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT)"
    assert _translate(sql) == (
        "CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY "
        "GENERATED BY DEFAULT AS IDENTITY)"
    )


def test_placeholder_ignored_inside_string_and_comment() -> None:
    sql = "SELECT '?', '??' AS q -- ?\n, ? FROM t"
    out = _translate(sql)
    # Inside literals and after -- comments the ? stays; the standalone ? becomes %s.
    assert "'?'" in out and "'??'" in out
    assert out.count("%s") == 1


def test_sqlite_double_question_collapses() -> None:
    # SQLite uses ?? for a literal question mark; PG has no escape, so it
    # collapses to a single literal ?.
    assert _translate("SELECT 'a??b'") == "SELECT 'a??b'"  # inside literal: untouched
    assert _translate("SELECT ??") == "SELECT ?"


def test_auto_increment_prefixed_identifier_is_left_alone() -> None:
    # "AUTOINCREMENT" as a quoted identifier/column name never occurs in the
    # framework DDL, but guard the tokenizer doesn't mangle such text.
    assert _translate('"AUTOINCREMENT"') == '"AUTOINCREMENT"'
