"""PostgreSQL implementation of the Voodoo database capability (Sprint 10).

An optional server backend behind the same ``VoodooDatabase`` protocol as
:class:`~voodoo.storage.database.sqlite.SQLiteDatabase` (spec §7, §11).
Enabled by ``database.provider: postgres`` in ``voodoo.yaml`` (or
``VOODOO_DATABASE_PROVIDER=postgres``) plus a ``url`` — install the
``[postgres]`` extra to use it.

Design notes:

- Uses psycopg 3 async. Rows use ``dict_row`` so ``row["name"]`` and
  ``row.keys()`` behave like aiosqlite rows.
- Client code (framework + application) writes ``?`` placeholders
  (SQLite-style); :meth:`PostgresDatabase._translate` rewrites ``?`` to
  psycopg's ``%s`` — with a small tokenizer so ``?`` inside string
  literals, quoted identifiers, and line/block comments is left alone,
  and pre-existing ``%s``/``$n`` placeholders are preserved.
- The single connection mirrors the aiosqlite singleton in
  :class:`SQLiteDatabase` (spec §49): one async connection per process,
  explicit commits per statement/transaction. Pooling is documented as a
  future option, not implemented here.
- ``execute()`` auto-commits after every statement exactly like the
  SQLite adapter, so call sites that rely on implicit commit keep
  working. ``transaction()`` gives a real commit/rollback block.

Capabilities are declared honestly: PG transactions, migrations, native
JSONB, and concurrent writers (MVCC) are all supported.
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from contextlib import asynccontextmanager
from typing import TYPE_CHECKING, Any

from voodoo.core.errors import ConfigurationError
from voodoo.storage.database.interfaces import (
    DatabaseCapabilities,
    Migration,
    VoodooDatabase,
)

LEDGER_TABLE = "schema_migrations"


def _skip_spans(query: str) -> list[tuple[int, int]]:
    """Spans of string literals / comments that must not be translated.

    ``'...'`` (with '' doubling), ``"..."`` identifiers, ``--`` line
    comments and ``/* ... */`` block comments are copied verbatim by the
    translator, so their offsets are collected up front.
    """
    spans: list[tuple[int, int]] = []
    i, n = 0, len(query)
    while i < n:
        ch = query[i]
        nxt = query[i + 1] if i + 1 < n else ""
        if ch == "'":
            j = i + 1
            while j < n:
                if query[j] == "'":
                    if j + 1 < n and query[j + 1] == "'":
                        j += 2
                        continue
                    break
                j += 1
            spans.append((i, j + 1))
            i = j + 1
        elif ch == '"':
            j = query.find('"', i + 1)
            j = n - 1 if j == -1 else j
            spans.append((i, j + 1))
            i = j + 1
        elif ch == "-" and nxt == "-":
            j = query.find("\n", i + 2)
            j = n - 1 if j == -1 else j
            spans.append((i, j + 1))
            i = j + 1
        elif ch == "/" and nxt == "*":
            j = query.find("*/", i + 2)
            j = n - 2 if j == -1 else j + 1
            spans.append((i, j + 1))
            i = j + 1
        else:
            i += 1
    return spans


def _translate(query: str) -> str:
    """Sqlite ``?`` placeholders to psycopg ``%s`` (+ AUTOINCREMENT → IDENTITY).

    Respects single/double-quoted literals, backticked/quoted identifiers,
    ``--`` line comments and ``/* */`` block comments, and leaves already-PG
    ``%s`` / ``$n`` placeholders alone (a ``?`` only becomes ``%s`` when not
    preceded by ``%``). SQLite's ``AUTOINCREMENT`` column clause is rewritten
    to the PG equivalent ``GENERATED BY DEFAULT AS IDENTITY`` so the
    framework's native migrations (which use it) run unchanged on either
    backend.
    """
    spans = _skip_spans(query)
    out: list[str] = []
    i, n = 0, len(query)
    while i < n:
        ch = query[i]
        if any(start <= i < end for start, end in spans):
            out.append(ch)
            i += 1
            continue
        nxt = query[i + 1] if i + 1 < n else ""
        if ch == "?":
            # A ? followed by ? is SQLite's escape for a literal ?;
            # PG supports ?? nothing, so collapse to a single literal ?.
            if nxt == "?":
                out.append("?")
                i += 2
            else:
                out.append("%s")
                i += 1
        elif ch.isalpha() and query[i : i + 13].upper() == "AUTOINCREMENT":
            out.append("GENERATED BY DEFAULT AS IDENTITY")
            i += len("AUTOINCREMENT")
        else:
            out.append(ch)
            i += 1
    return "".join(out)


class _PgConnection:
    """Thin adapter around a psycopg ``AsyncConnection``.

    Exposes the same surface the framework's ``get_db()``-driven data layer
    expects from the connection it publishes: ``execute`` (with SQLite-style
    ``?`` placeholders auto-translated), ``commit``, ``rollback``, ``close``.
    With ``autocommit=True`` each ``execute`` is applied immediately (the
    SQLite adapter commits per statement too); ``transaction()`` blocks on
    the adapters use psycopg's ``transaction()`` which still gives real
    atomic commit/rollback.
    """

    def __init__(self, raw: Any):
        self._raw = raw

    # Keep ``row_factory``/``dict_row`` readable for callers that set it.
    @property
    def row_factory(self) -> Any:
        return self._raw.row_factory

    @row_factory.setter
    def row_factory(self, value: Any) -> None:
        self._raw.row_factory = value

    async def execute(self, query: str, params: Sequence[Any] = ()) -> Any:
        from psycopg.rows import dict_row

        if self._raw.row_factory is None:
            self._raw.row_factory = dict_row
        return await self._raw.execute(_translate(query), tuple(params))

    async def commit(self) -> None:
        await self._raw.commit()

    async def rollback(self) -> None:
        await self._raw.rollback()

    async def close(self) -> None:
        await self._raw.close()

    async def __aenter__(self) -> _PgConnection:
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.close()


class PostgresDatabase:
    """Server-backed PostgreSQL backend behind the VoodooDatabase protocol."""

    provider = "postgres"

    def __init__(self, url: str, migrations: Sequence[Migration] = ()) -> None:
        if not url:
            raise ConfigurationError(
                "PostgreSQL database requires a URL: set database.url in "
                "voodoo.yaml, or export VOODOO_DATABASE_URL."
            )
        self.url = url
        self._extra_migrations = tuple(migrations)
        self._conn: Any | None = None  # psycopg AsyncConnection when open
        self._version = 0
        # Early validation: duplicates among explicitly-provided migrations
        # are caught at construction (same as the SQLite adapter).
        self._merge_migrations()

    def _merge_migrations(self) -> tuple[Migration, ...]:
        from voodoo.storage.database import FRAMEWORK_MIGRATIONS

        by_version: dict[int, Migration] = {}
        for migration in (*FRAMEWORK_MIGRATIONS, *self._extra_migrations):
            if migration.version in by_version:
                raise ValueError(
                    f"duplicate migration version {migration.version} "
                    f"({by_version[migration.version].name!r} vs {migration.name!r})"
                )
            by_version[migration.version] = migration
        return tuple(by_version[v] for v in sorted(by_version))

    @property
    def connection(self) -> _PgConnection:
        if self._conn is None:
            raise RuntimeError(
                f"postgres database at {self.url!r} is not connected; "
                "call connect() first"
            )
        return _PgConnection(self._conn)

    def _raw(self) -> Any:
        """The live psycopg connection, or a clear error if not connected."""
        if self._conn is None:
            raise RuntimeError(
                f"postgres database at {self.url!r} is not connected; "
                "call connect() first"
            )
        return self._conn

    # -- lifecycle -----------------------------------------------------------

    async def connect(self) -> None:
        if self._conn is not None:
            return
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:  # pragma: no cover - import guard
            raise ConfigurationError(
                "The postgres database provider requires the [postgres] extra: "
                "pip install 'voodoo-framework[postgres]' (psycopg[binary])."
            ) from exc
        self._conn = await psycopg.AsyncConnection.connect(
            self.url,
            # Each statement applies immediately (mirrors the SQLite
            # adapter's per-statement commit). transaction() below still
            # gives atomic commit/rollback via psycopg's explicit
            # transaction block.
            autocommit=True,
        )
        # dict rows so ``row["name"]`` / ``row.keys()`` behave like aiosqlite.
        self._conn.row_factory = dict_row

    async def close(self) -> None:
        if self._conn is not None:
            try:
                await self._conn.close()
            finally:
                self._conn = None

    # -- migrations ----------------------------------------------------------

    async def migrate(self) -> None:
        raw = self._raw()
        await raw.execute(
            f"CREATE TABLE IF NOT EXISTS {LEDGER_TABLE} ("
            "version INTEGER PRIMARY KEY,"
            "name TEXT NOT NULL,"
            "applied_at TIMESTAMPTZ NOT NULL DEFAULT now())"
        )

        applied = {
            row["version"]
            for row in await self.fetch_all(f"SELECT version FROM {LEDGER_TABLE}")
        }
        # Re-merge each time so late-imported subsystem migrations are picked up.
        for migration in self._merge_migrations():
            if migration.version not in applied:
                async with raw.transaction():
                    for statement in migration.statements:
                        await raw.execute(_translate(statement))
                    if migration.fn is not None:
                        await migration.fn(self)
                    await raw.execute(
                        f"INSERT INTO {LEDGER_TABLE} (version, name) VALUES (%s, %s)",
                        (migration.version, migration.name),
                    )
                self._version = migration.version
            elif migration.rerun and migration.fn is not None:
                await migration.fn(self)

        # This instance may be a fresh handle onto an already-migrated
        # database (contract tests, reconnect, second process): derive the
        # version from the ledger rather than only the migrations this call
        # applied.
        rows = await self.fetch_all(f"SELECT version FROM {LEDGER_TABLE}")
        self._version = max((row["version"] for row in rows), default=0)

    def current_version(self) -> int:
        return self._version

    # -- queries -------------------------------------------------------------

    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[Any]:
        """Commit on success, rollback on error (real PG transaction)."""
        raw = self._raw()
        async with raw.transaction():
            yield _PgConnection(raw)

    async def execute(self, query: str, params: Sequence[Any] = ()) -> Any:
        """Run one statement. Returns the psycopg cursor.

        With autocommit the statement is applied immediately; the returned
        cursor is usable for ``fetchone()``/``rowcount`` where needed.
        (The data layer computes row ids via ``RETURNING`` rather than
        ``lastrowid``, which psycopg does not expose.)
        """
        return await self._raw().execute(_translate(query), tuple(params))

    async def fetch_all(self, query: str, params: Sequence[Any] = ()) -> list[Any]:
        async with self._raw().cursor() as cursor:
            await cursor.execute(_translate(query), params)
            rows = await cursor.fetchall()
        return list(rows)

    async def fetch_one(self, query: str, params: Sequence[Any] = ()) -> Any | None:
        async with self._raw().cursor() as cursor:
            await cursor.execute(_translate(query), params)
            return await cursor.fetchone()

    # Raw-connection passthroughs so ``get_db()``-driven code that calls
    # ``db.commit()`` on the published connection keeps working.
    async def commit(self) -> None:
        await self._raw().commit()

    async def rollback(self) -> None:
        await self._raw().rollback()

    def capabilities(self) -> DatabaseCapabilities:
        return DatabaseCapabilities(
            provider=self.provider,
            transactions=True,
            migrations=True,
            native_json=True,  # JSONB
            concurrent_writers=True,  # MVCC
        )


if TYPE_CHECKING:
    # Structural conformance assertion — mypy errors here if the adapter
    # drifts from the VoodooDatabase protocol.
    _protocol_check: VoodooDatabase = PostgresDatabase("postgresql://check")
