"""The Voodoo UI system: component model, library, interaction runtime, and styles.

New application code should import components from this module. Interactive
components accept Python callables directly and keep browser mechanics inside
Voodoo::

    from voodoo.ui import Button

    async def save():
        ...

    Button("Save", on_click=save)
"""

from voodoo.ui.brand import Brand
from voodoo.ui.component import Component, Html, escape, tone_to_color_var
from voodoo.ui.controls import (
    Calendar,
    CheckboxGroup,
    Combobox,
    DatePicker,
    DropZone,
    FileUpload,
    InputGroup,
    MultiSelect,
    NumberInput,
    PasswordInput,
    RadioGroup,
    SearchInput,
    Slider,
    TimePicker,
)
from voodoo.ui.data_extended import (
    ColumnDef,
    DataList,
    DataRow,
    DescriptionItem,
    DescriptionList,
    DescriptionSection,
    EnhancedDataTable,
    ListBox,
    ListOption,
    StatGroup,
)
from voodoo.ui.data_extended import (
    Stat as DataStat,
)
from voodoo.ui.events import UIEvent
from voodoo.ui.forms_extended import (
    Autocomplete,
    CheckboxInput,
    FormError,
    FormValidationSummary,
    OTPInput,
    RadioInput,
    RangeSlider,
)
from voodoo.ui.foundation import (
    Accordion,
    AccordionItem,
    Alert,
    AspectRatio,
    Breadcrumb,
    BreadcrumbItem,
    ButtonGroup,
    Kbd,
    Progress,
    Spinner,
)
from voodoo.ui.interaction_kernel import (
    AlertDialog,
    AlertDialogTrigger,
    Command,
    CommandGroup,
    CommandPalette,
    ContextMenu,
    DismissLayer,
    LayerManager,
    MenuCheckboxItem,
    MenuGroup,
    MenuRadioItem,
    Portal,
    Segment,
    SegmentedControl,
    SubMenu,
    ToggleGroup,
    ToggleItem,
)
from voodoo.ui.interactions import (
    Drawer,
    DropdownMenu,
    MenuItem,
    MenuSeparator,
    ModalClose,
    ModalTrigger,
    Snackbar,
    Tab,
    Tabs,
    Toast,
    ToastRegion,
)
from voodoo.ui.interactive import (
    Button,
    Checkbox,
    Composer,
    Form,
    Input,
    Radio,
    Select,
    Textarea,
    ThemeToggle,
)
from voodoo.ui.layout import Page
from voodoo.ui.library import (
    A,
    Address,
    Article,
    Aside,
    AuthGuard,
    Avatar,
    BackLink,
    Badge,
    Box,
    Card,
    ChatBox,
    ChatMessage,
    Chip,
    CodeBlock,
    Container,
    CTABand,
    Dialog,
    Div,
    Divider,
    Eyebrow,
    FeatureCard,
    FigCaption,
    Figure,
    Flex,
    Footer,
    Grid,
    Header,
    Heading,
    Hero,
    Icon,
    Img,
    Label,
    Link,
    LinkArrow,
    List,
    ListItem,
    LoginForm,
    Main,
    Markdown,
    MessageList,
    Modal,
    Nav,
    Navbar,
    NavLink,
    Option,
    PageHero,
    Paragraph,
    RegisterForm,
    Section,
    Sidebar,
    Stack,
    Stat,
    Stats,
    StreamingText,
    Table,
    Text,
    Time,
    UserBadge,
)
from voodoo.ui.navigation import (
    AppShell,
    BottomNav,
    BottomNavItem,
    SidebarItem,
    SidebarToggle,
)
from voodoo.ui.navigation_extended import (
    Action,
    ActionSheet,
    AnchorLink,
    AnchorNavigation,
    BottomSheet,
    NavColumn,
    NavContent,
    NavigationMenu,
    NavLinkItem,
    NavTrigger,
    Pagination,
    Step,
    Stepper,
    TopBar,
)
from voodoo.ui.primitives import Field, Popover, Skeleton, Switch, Tooltip
from voodoo.ui.product import (
    Column,
    CommandBar,
    DataTable,
    EmptyState,
    EventRow,
    InspectorPanel,
    LogViewer,
    Metric,
    StatusBadge,
    Timeline,
)
from voodoo.ui.styles import (
    NoopAdapter,
    StyleAdapter,
    ThemePalette,
    color,
    current_adapter,
    set_style_adapter,
)
from voodoo.ui.voodoo_system import (
    AgentStatus,
    ApprovalCard,
    CapabilityList,
    DeviceCard,
    EdgeNode,
    ExecutionStatus,
    ExecutionTimeline,
    ObservationFeed,
    PolicyDecision,
    RuntimeStatus,
    TelemetryPanel,
    WorldEntityInspector,
)
from voodoo.ui.workspace import (
    DetailPane,
    Dock,
    DockItem,
    KeyBinding,
    KeyboardShortcutRegistry,
    MasterDetail,
    MasterItem,
    MasterList,
    Menubar,
    MenubarItem,
    MenubarMenu,
    MenubarSeparator,
    Panel,
    ResizablePanels,
    ScrollArea,
    Toolbar,
    ToolbarButton,
    ToolbarGroup,
    ToolbarSeparator,
    TreeNode,
    TreeView,
)

__all__ = [
    # Component model
    "Component",
    "Html",
    "UIEvent",
    "escape",
    "tone_to_color_var",
    # Style adapters
    "StyleAdapter",
    "NoopAdapter",
    "ThemePalette",
    "color",
    "set_style_adapter",
    "current_adapter",
    # Icons & Markdown
    "Icon",
    "Markdown",
    # Chat primitives
    "MessageList",
    "ChatMessage",
    "StreamingText",
    "Composer",
    "ChatBox",
    # Layout
    "Div",
    "Flex",
    "Stack",
    "Grid",
    "Box",
    "Container",
    "Page",
    # Core elements
    "A",
    "Link",
    "Button",
    "Card",
    "Text",
    "Heading",
    "Badge",
    "Avatar",
    "Divider",
    "Dialog",
    "Modal",
    "Popover",
    "Tooltip",
    "Skeleton",
    "Alert",
    "Progress",
    "Spinner",
    "Breadcrumb",
    "BreadcrumbItem",
    "ButtonGroup",
    "Accordion",
    "AccordionItem",
    "Kbd",
    "AspectRatio",
    "Drawer",
    "DropdownMenu",
    "MenuItem",
    "MenuSeparator",
    "ModalTrigger",
    "ModalClose",
    "Tabs",
    "Tab",
    "ToastRegion",
    "Toast",
    "Snackbar",
    # Forms
    "Form",
    "Field",
    "Label",
    "Input",
    "Textarea",
    "Select",
    "Option",
    "Checkbox",
    "Radio",
    "Switch",
    # Controls (existing, now exported)
    "Calendar",
    "CheckboxGroup",
    "Combobox",
    "DatePicker",
    "DropZone",
    "FileUpload",
    "InputGroup",
    "MultiSelect",
    "NumberInput",
    "PasswordInput",
    "RadioGroup",
    "SearchInput",
    "Slider",
    "TimePicker",
    # Priority 1 — Interaction Kernel
    "AlertDialog",
    "AlertDialogTrigger",
    "Command",
    "CommandGroup",
    "CommandPalette",
    "ContextMenu",
    "DismissLayer",
    "LayerManager",
    "MenuCheckboxItem",
    "MenuGroup",
    "MenuRadioItem",
    "Portal",
    "Segment",
    "SegmentedControl",
    "SubMenu",
    "ToggleGroup",
    "ToggleItem",
    # Priority 2 — Complete Forms
    "Autocomplete",
    "CheckboxInput",
    "FormError",
    "FormValidationSummary",
    "OTPInput",
    "RadioInput",
    "RangeSlider",
    # Priority 3 — Adaptive Navigation
    "Action",
    "ActionSheet",
    "AnchorLink",
    "AnchorNavigation",
    "BottomSheet",
    "NavColumn",
    "NavContent",
    "NavigationMenu",
    "NavLinkItem",
    "NavTrigger",
    "Pagination",
    "Step",
    "Stepper",
    "TopBar",
    # Priority 4 — Desktop Workspaces
    "DetailPane",
    "Dock",
    "DockItem",
    "KeyBinding",
    "KeyboardShortcutRegistry",
    "MasterDetail",
    "MasterItem",
    "MasterList",
    "Menubar",
    "MenubarItem",
    "MenubarMenu",
    "MenubarSeparator",
    "Panel",
    "ResizablePanels",
    "ScrollArea",
    "Toolbar",
    "ToolbarButton",
    "ToolbarGroup",
    "ToolbarSeparator",
    "TreeNode",
    "TreeView",
    # Priority 5 — Data-Heavy Interfaces
    "ColumnDef",
    "DataList",
    "DataRow",
    "DataStat",
    "DescriptionItem",
    "DescriptionList",
    "DescriptionSection",
    "EnhancedDataTable",
    "ListBox",
    "ListOption",
    "StatGroup",
    # Product components
    "StatusBadge",
    "Metric",
    "EmptyState",
    "Column",
    "DataTable",
    "EventRow",
    "Timeline",
    "InspectorPanel",
    "LogViewer",
    "CommandBar",
    # Voodoo system components
    "RuntimeStatus",
    "AgentStatus",
    "DeviceCard",
    "ExecutionStatus",
    "ExecutionTimeline",
    "ApprovalCard",
    "WorldEntityInspector",
    "ObservationFeed",
    "CapabilityList",
    "PolicyDecision",
    "EdgeNode",
    "TelemetryPanel",
    # Collections
    "Table",
    "List",
    "ListItem",
    "Sidebar",
    "AppShell",
    "BottomNav",
    "BottomNavItem",
    "SidebarItem",
    "SidebarToggle",
    # Semantic structure
    "Nav",
    "Header",
    "Footer",
    "Main",
    "Section",
    "Article",
    "Aside",
    "Figure",
    "FigCaption",
    "Address",
    "Paragraph",
    "Time",
    "Img",
    # Chrome
    "Navbar",
    "NavLink",
    "Brand",
    "ThemeToggle",
    "Hero",
    "PageHero",
    "Eyebrow",
    "Chip",
    "CodeBlock",
    "Stats",
    "Stat",
    "CTABand",
    "BackLink",
    "FeatureCard",
    "LinkArrow",
    # Auth UI
    "LoginForm",
    "RegisterForm",
    "UserBadge",
    "AuthGuard",
]
