"""The Voodoo UI system: component model, library, and style adapters.

Import the component library from here::

    from voodoo.ui import Button, Card, Page, Stack, Link

Styling is pluggable — swap the CSS framework without touching components::

    from voodoo.ui import set_style_adapter, NoopAdapter
    set_style_adapter(NoopAdapter())
"""

from voodoo.ui.component import Component, Html, escape, tone_to_color_var
from voodoo.ui.library import (
    A,
    Address,
    Article,
    Aside,
    AuthGuard,
    Avatar,
    BackLink,
    Badge,
    Box,
    Brand,
    Button,
    Card,
    ChatBox,
    ChatMessage,
    Checkbox,
    Chip,
    CodeBlock,
    Composer,
    Container,
    CTABand,
    Dialog,
    Div,
    Divider,
    Eyebrow,
    FeatureCard,
    FigCaption,
    Figure,
    Flex,
    Footer,
    Form,
    Grid,
    Header,
    Heading,
    Hero,
    Icon,
    Img,
    Input,
    Label,
    Link,
    LinkArrow,
    List,
    ListItem,
    LoginForm,
    Main,
    Markdown,
    MessageList,
    Modal,
    Nav,
    Navbar,
    NavLink,
    Option,
    Page,
    PageHero,
    Paragraph,
    Radio,
    RegisterForm,
    Section,
    Select,
    Sidebar,
    Stack,
    Stat,
    Stats,
    StreamingText,
    Table,
    Text,
    Textarea,
    ThemeToggle,
    Time,
    UserBadge,
)
from voodoo.ui.styles import (
    NoopAdapter,
    StyleAdapter,
    current_adapter,
    set_style_adapter,
)

__all__ = [
    # Component model
    "Component",
    "Html",
    "escape",
    "tone_to_color_var",
    # Style adapters
    "StyleAdapter",
    "NoopAdapter",
    "set_style_adapter",
    "current_adapter",
    # Icons & Markdown
    "Icon",
    "Markdown",
    # Chat primitives
    "MessageList",
    "ChatMessage",
    "StreamingText",
    "Composer",
    "ChatBox",
    # Layout
    "Div",
    "Flex",
    "Stack",
    "Grid",
    "Box",
    "Container",
    "Page",
    # Core elements
    "A",
    "Link",
    "Button",
    "Card",
    "Text",
    "Heading",
    "Badge",
    "Avatar",
    "Divider",
    "Dialog",
    "Modal",
    # Forms
    "Form",
    "Label",
    "Input",
    "Textarea",
    "Select",
    "Option",
    "Checkbox",
    "Radio",
    # Collections
    "Table",
    "List",
    "ListItem",
    "ChatBox",
    "Sidebar",
    # Semantic structure
    "Nav",
    "Header",
    "Footer",
    "Main",
    "Section",
    "Article",
    "Aside",
    "Figure",
    "FigCaption",
    "Address",
    "Paragraph",
    "Time",
    "Img",
    # Chrome
    "Navbar",
    "NavLink",
    "Brand",
    "ThemeToggle",
    "Hero",
    "PageHero",
    "Eyebrow",
    "Chip",
    "CodeBlock",
    "Stats",
    "Stat",
    "CTABand",
    "BackLink",
    "FeatureCard",
    "LinkArrow",
    # Auth UI
    "LoginForm",
    "RegisterForm",
    "UserBadge",
    "AuthGuard",
]
