"""The native Voodoo CSS adapter.

Returns semantic class names (``vd-button``, ``vd-button--primary``). The
matching CSS is generated by :func:`generate_component_css` and included in
``render_page``. All values reference ``--vd-*`` tokens, so changing the
theme at runtime changes every component without re-rendering.

This is the default adapter. Tailwind is opt-in::

    from voodoo import TailwindAdapter, set_style_adapter
    set_style_adapter(TailwindAdapter())
"""

from __future__ import annotations

from typing import Any

from voodoo.ui.styles.theme import Theme


class VoodooCSSAdapter:
    """Returns semantic ``vd-*`` class names resolved by generated CSS."""

    def component_classes(
        self, component: str, props: dict[str, Any], theme: Theme
    ) -> str:
        # Build BEM-style class names from the semantic key + props
        base = component.replace(".", "-")
        classes: list[str] = [f"vd-{base}"]

        variant = props.get("variant")
        if variant:
            classes.append(f"vd-{base}--{variant}")

        # Heading level
        level = props.get("level")
        if level and component == "heading":
            classes.append(f"vd-{base}--h{level}")

        # Chat message role (user | assistant | system | tool)
        role = props.get("role")
        if role and component == "chat-message":
            classes.append(f"vd-{base}--{role}")

        # Streaming text terminal state (caret hidden when done)
        if component == "streaming-text" and props.get("done"):
            classes.append(f"vd-{base}--done")

        # Size — button/input use it directly
        if component in ("button", "input"):
            size = props.get("size")
            if size and size != "md":
                classes.append(f"vd-{base}--{size}")

        classes.extend(self._layout_classes(component, props))
        return " ".join(classes)

    def _layout_classes(self, component: str, props: dict[str, Any]) -> list[str]:
        """Layout modifier classes (Flex/Grid/Container/Page/List)."""
        classes: list[str] = []

        if component == "flex":
            classes.extend(self._flex_classes(props))

        if component == "grid":
            classes.append(f"vd-grid--cols-{props.get('cols', '1')}")
            classes.append(f"vd-grid--gap-{props.get('gap', '4')}")

        if component == "container":
            classes.append(f"vd-container--{props.get('size', 'xl')}")
            if props.get("centered", True):
                classes.append("vd-container--centered")

        if component == "page":
            classes.append(f"vd-page--{props.get('size', 'lg')}")
            if props.get("pad", True):
                classes.append("vd-page--pad")

        if component == "list":
            classes.extend(self._list_classes(props))

        classes.extend(self._app_shell_classes(component, props))
        classes.extend(self._card_classes(component, props))
        classes.extend(self._foundation_classes(component, props))
        classes.extend(self._chrome_classes(component, props))
        return classes

    @staticmethod
    def _app_shell_classes(component: str, props: dict[str, Any]) -> list[str]:
        if component != "app-shell.content":
            return []
        return [f"vd-app-shell-content--pad-{props.get('padding', 'lg')}"]

    @staticmethod
    def _card_classes(component: str, props: dict[str, Any]) -> list[str]:
        if component != "card":
            return []

        classes: list[str] = []
        padding = props.get("padding", "lg")
        if padding != "lg":
            classes.append(f"vd-card--pad-{padding}")
        if props.get("interactive") and props.get("variant") != "interactive":
            classes.append("vd-card--interactive")
        return classes

    @staticmethod
    def _foundation_classes(component: str, props: dict[str, Any]) -> list[str]:
        """Modifier classes for feedback, navigation and disclosure primitives."""
        return VoodooCSSAdapter._feedback_classes(
            component, props
        ) + VoodooCSSAdapter._interaction_classes(component, props)

    @staticmethod
    def _feedback_classes(component: str, props: dict[str, Any]) -> list[str]:
        classes: list[str] = []
        if component in {"alert", "progress"}:
            classes.append(f"vd-{component}--{props.get('tone', 'primary')}")
        if component in {"progress", "spinner"}:
            size = props.get("size", "md")
            if size != "md":
                classes.append(f"vd-{component}--{size}")
        if component == "toast-region":
            classes.append(f"vd-toast-region--{props.get('position', 'bottom-right')}")
        if component == "toast":
            classes.extend(
                (
                    f"vd-toast--{props.get('tone', 'default')}",
                    f"vd-toast--{props.get('variant', 'toast')}",
                )
            )
        return classes

    @staticmethod
    def _interaction_classes(component: str, props: dict[str, Any]) -> list[str]:
        classes: list[str] = []
        if component == "button-group":
            classes.append(f"vd-button-group--{props.get('orientation', 'horizontal')}")
            if props.get("attached", True):
                classes.append("vd-button-group--attached")
        if component == "sidebar":
            classes.append(f"vd-sidebar--{props.get('mode', 'expanded')}")
        if component == "sidebar-toggle":

        if component == "sidebar-item" and props.get("active"):
            classes.append("vd-sidebar-item--active")
        if component == "bottom-nav-item" and props.get("active"):
            classes.append("vd-bottom-nav-item--active")
        if component == "drawer":
            classes.extend(
                (
                    f"vd-drawer--{props.get('side', 'left')}",
                    f"vd-drawer--{props.get('size', 'md')}",
                )
            )
        if component == "menu-item" and props.get("destructive"):
            classes.append("vd-menu-item--destructive")
        if component == "tabs":
            classes.append(f"vd-tabs--{props.get('orientation', 'horizontal')}")
        return classes

    @staticmethod
    def _chrome_classes(component: str, props: dict[str, Any]) -> list[str]:
        """Modifier classes for page-level chrome components."""
        if component == "navbar" and props.get("sticky", True):
            return ["vd-navbar--sticky"]
        if component == "nav-link" and props.get("active"):
            return ["vd-nav-link--active"]
        if component == "stats":
            return [f"vd-stats--cols-{props.get('cols', '3')}"]
        return []

    @staticmethod
    def _flex_classes(props: dict[str, Any]) -> list[str]:
        direction = props.get("direction", "row")
        justify = props.get("justify", "start")
        items = props.get("items", "stretch")
        wrap = props.get("wrap", "nowrap")
        return [
            _FLEX_DIRECTIONS.get(direction, "vd-flex--row"),
            f"vd-flex--justify-{justify if justify in _FLEX_JUSTIFY else 'start'}",
            f"vd-flex--items-{items if items in _FLEX_ITEMS else 'stretch'}",
            f"vd-flex--{wrap if wrap in _FLEX_WRAP else 'nowrap'}",
            f"vd-flex--gap-{props.get('gap', '0')}",
        ]

    @staticmethod
    def _list_classes(props: dict[str, Any]) -> list[str]:
        if props.get("unstyled"):
            return ["vd-list--unstyled"]
        if props.get("ordered"):
            return ["vd-list--ordered"]
        return []


# Layout modifier vocabularies shared by the adapter and the generated CSS
_FLEX_DIRECTIONS = {
    "row": "vd-flex--row",
    "col": "vd-flex--col",
    "row-reverse": "vd-flex--row-reverse",
    "col-reverse": "vd-flex--col-reverse",
}
_FLEX_JUSTIFY = {"start", "end", "center", "between", "around", "evenly"}
_FLEX_ITEMS = {"start", "end", "center", "baseline", "stretch"}
_FLEX_WRAP = {"nowrap", "wrap", "wrap-reverse"}
_GAP_SCALE = [
    "0",
    "xs",
    "sm",
    "md",
    "lg",
    "xl",
    "xxl",
    "xxxl",
] + [str(i) for i in range(1, 13)]
_CONTAINER_SIZES = {
    "sm": "40rem",
    "md": "48rem",
    "lg": "64rem",
    "xl": "80rem",
    "2xl": "96rem",
    "full": "100%",
}


# ---------------------------------------------------------------------------
# CSS generation — produces the stylesheet for all vd-* classes
# ---------------------------------------------------------------------------


def generate_component_css(theme: Theme) -> str:
    """Generate CSS for all ``vd-*`` component classes.

    Uses ``--vd-*`` tokens exclusively so theme changes propagate instantly.
    Includes a base reset, a type scale, full component coverage, and layout
    modifier classes matching :class:`VoodooCSSAdapter`.
    """
    r = "var(--vd-radius-"
    s = "var(--vd-space-"
    t = "var(--vd-text-"
    sh = "var(--vd-shadow-"
    m = "var(--vd-motion-"

    return f"""
/* ── Voodoo Component CSS (generated) ─────────────────────────────── */

/* Base reset */
*, *::before, *::after {{
    box-sizing: border-box; margin: 0; padding: 0;
}}
html {{ -webkit-text-size-adjust: 100%; text-size-adjust: 100%; }}
body {{
    font-family: var(--vd-font-sans); font-size: {t}md);
    line-height: var(--vd-leading-normal); color: var(--vd-color-text);
    background: var(--vd-color-background); min-height: 100vh;
    -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
}}
img, svg, video, canvas {{ display: block; max-width: 100%; }}
button, input, select, textarea {{ font: inherit; color: inherit; }}
:focus-visible {{ outline: 2px solid var(--vd-color-secondary); outline-offset: 2px; }}
::selection {{ background: var(--vd-color-secondary); color: var(--vd-color-on-secondary); }}

/* Typography */
.vd-paragraph {{
    font-size: {t}md); line-height: var(--vd-leading-normal);
    color: var(--vd-color-text-muted); max-width: 65ch;
}}
.vd-text {{ color: var(--vd-color-text); }}
.vd-text--muted {{ color: var(--vd-color-text-muted); }}
.vd-text--primary {{ color: var(--vd-color-primary); }}
.vd-text--success {{ color: var(--vd-color-success); }}
.vd-text--warning {{ color: var(--vd-color-warning); }}
.vd-text--danger {{ color: var(--vd-color-danger); }}

/* Button */
.vd-button {{
    display: inline-flex; align-items: center; justify-content: center;
    gap: {s}sm); white-space: nowrap;
    border-radius: {r}md); font-size: {t}sm); font-weight: var(--vd-weight-medium);
    transition: background {m}normal), color {m}normal), border-color {m}normal),
        box-shadow {m}normal), opacity {m}normal), transform {m}fast);
    border: 1px solid var(--vd-color-border); cursor: pointer; outline: none;
    background: var(--vd-color-surface); color: var(--vd-color-text);
    height: 2.25rem; padding: 0 1rem;
}}
.vd-button:hover {{ background: var(--vd-color-surface-raised); }}
.vd-button:active {{ transform: translateY(1px); }}
.vd-button:focus-visible {{ box-shadow: 0 0 0 2px var(--vd-color-secondary); }}
.vd-button:disabled {{ pointer-events: none; opacity: 0.5; }}
.vd-button--primary {{
    background: var(--vd-color-primary); color: var(--vd-color-on-primary);
}}
.vd-button--primary:hover {{ background: var(--vd-color-primary-hover); }}
.vd-button--secondary {{
    background: var(--vd-color-secondary); color: var(--vd-color-on-secondary);
}}
.vd-button--secondary:hover {{ opacity: 0.9; }}
.vd-button--outline {{
    border: 1px solid var(--vd-color-border); background: transparent;
    color: var(--vd-color-text);
}}
.vd-button--outline:hover {{ background: var(--vd-color-surface); }}
.vd-button--ghost {{
    background: transparent; color: var(--vd-color-text-muted);
}}
.vd-button--ghost:hover {{
    background: var(--vd-color-surface); color: var(--vd-color-text);
}}
.vd-button--danger {{
    background: var(--vd-color-danger); color: #fff;
}}
.vd-button--danger:hover {{ opacity: 0.9; }}
.vd-button--sm {{ height: 2rem; padding: 0 0.75rem; font-size: {t}xs); }}
.vd-button--lg {{ height: 2.5rem; padding: 0 1.5rem; font-size: {t}md); }}

/* Card */
.vd-card {{
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-radius: {r}xl); padding: {s}xl);
    box-shadow: {sh}sm);
}}
.vd-card--elevated {{
    background: var(--vd-color-surface-raised); box-shadow: {sh}md);
}}
.vd-card--outline {{ background: transparent; box-shadow: none; }}
.vd-card--ghost {{ background: transparent; border-color: transparent; box-shadow: none; }}
.vd-card--interactive {{
    cursor: pointer; transition: transform {m}normal), border-color {m}normal),
        box-shadow {m}normal);
}}
.vd-card--interactive:hover {{ transform: translateY(-2px); box-shadow: {sh}md); }}
.vd-card--pad-none {{ padding: 0; }}
.vd-card--pad-sm {{ padding: {s}sm); }}
.vd-card--pad-md {{ padding: {s}md); }}
.vd-card--pad-xl {{ padding: {s}xxl); }}

/* Form */
.vd-form {{ display: flex; flex-direction: column; gap: {s}md); }}

/* Label */
.vd-label {{
    display: block; font-size: {t}sm); font-weight: var(--vd-weight-medium);
    line-height: 1; color: var(--vd-color-text);
}}

/* Input */
.vd-input {{
    display: flex; width: 100%; height: 2.25rem;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.25rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    transition: border-color {m}normal), box-shadow {m}normal);
}}
.vd-input::placeholder {{ color: var(--vd-color-text-muted); }}
.vd-input:focus-visible {{
    outline: none; border-color: var(--vd-color-secondary);
    box-shadow: 0 0 0 1px var(--vd-color-secondary);
}}
.vd-input:disabled {{ opacity: 0.5; cursor: not-allowed; }}
.vd-input--sm {{ height: 2rem; padding: 0.25rem 0.625rem; }}
.vd-input--lg {{ height: 2.75rem; padding: 0.5rem 1rem; }}

/* Textarea */
.vd-textarea {{
    display: flex; min-height: 80px; width: 100%;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.5rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    transition: border-color {m}normal);
}}
.vd-textarea:focus-visible {{
    outline: none; border-color: var(--vd-color-secondary);
    box-shadow: 0 0 0 1px var(--vd-color-secondary);
}}

/* Select */
.vd-select {{
    display: flex; width: 100%; height: 2.25rem; align-items: center;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.5rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    cursor: pointer;
}}
.vd-select:focus {{ outline: none; border-color: var(--vd-color-secondary); }}
.vd-option {{ color: var(--vd-color-text); background: var(--vd-color-surface); }}

/* Checkbox */
.vd-checkbox {{
    width: 1rem; height: 1rem; border: 1px solid var(--vd-color-border);
    border-radius: {r}sm); cursor: pointer; accent-color: var(--vd-color-secondary);
}}

/* Radio */
.vd-radio {{
    width: 1rem; height: 1rem; border: 1px solid var(--vd-color-border);
    border-radius: {r}full); cursor: pointer; accent-color: var(--vd-color-secondary);
}}

/* Heading */
.vd-heading {{
    color: var(--vd-color-text); font-weight: var(--vd-weight-bold);
    line-height: var(--vd-leading-tight); letter-spacing: -0.025em;
    text-wrap: balance;
}}
.vd-heading--h1 {{ font-size: {t}xxxl); font-weight: var(--vd-weight-bold); }}
.vd-heading--h2 {{ font-size: {t}xxl); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h3 {{ font-size: {t}xl); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h4 {{ font-size: {t}lg); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h5 {{ font-size: {t}md); font-weight: var(--vd-weight-medium); }}
.vd-heading--h6 {{ font-size: {t}sm); font-weight: var(--vd-weight-medium); }}

/* Badge */
.vd-badge {{
    display: inline-flex; align-items: center; border-radius: {r}full);
    padding: 0.125rem 0.625rem; font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    transition: background {m}normal);
}}
.vd-badge--default {{ background: var(--vd-color-text); color: var(--vd-color-surface); }}
.vd-badge--secondary {{
    background: var(--vd-color-surface); color: var(--vd-color-text);
    border: 1px solid var(--vd-color-border);
}}
.vd-badge--outline {{ color: var(--vd-color-text); border: 1px solid var(--vd-color-border); }}
.vd-badge--success {{ background: var(--vd-color-success); color: #fff; }}
.vd-badge--warning {{ background: var(--vd-color-warning); color: #000; }}
.vd-badge--danger {{ background: var(--vd-color-danger); color: #fff; }}

/* Avatar */
.vd-avatar {{
    position: relative; display: flex; height: 2.5rem; width: 2.5rem;
    overflow: hidden; border-radius: {r}full); flex-shrink: 0;
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
}}
.vd-avatar-img {{ height: 100%; width: 100%; object-fit: cover; }}
.vd-avatar-fallback {{
    display: flex; height: 100%; width: 100%; align-items: center;
    justify-content: center; border-radius: {r}full);
    background: var(--vd-color-surface);
    color: var(--vd-color-text); font-size: {t}sm); font-weight: var(--vd-weight-medium);
}}

/* Feedback */
.vd-alert {{
    --vd-alert-color: var(--vd-color-info);
    display: grid; gap: {s}xs); padding: {s}md) {s}lg);
    border: 1px solid color-mix(in srgb, var(--vd-alert-color) 28%, transparent);
    border-radius: {r}lg);
    background: color-mix(in srgb, var(--vd-alert-color) 8%, transparent);
    color: var(--vd-color-text);
}}
.vd-alert--primary {{ --vd-alert-color: var(--vd-color-primary); }}
.vd-alert--info {{ --vd-alert-color: var(--vd-color-info); }}
.vd-alert--success {{ --vd-alert-color: var(--vd-color-success); }}
.vd-alert--warning {{ --vd-alert-color: var(--vd-color-warning); }}
.vd-alert--danger {{ --vd-alert-color: var(--vd-color-danger); }}
.vd-alert--outline {{ background: transparent; }}
.vd-alert--solid {{
    background: var(--vd-alert-color); border-color: var(--vd-alert-color); color: white;
}}
.vd-alert--solid.vd-alert--warning {{ color: #171717; }}
.vd-alert-title {{ font-size: {t}sm); font-weight: var(--vd-weight-semibold); }}
.vd-alert-content {{ font-size: {t}sm); line-height: 1.55; color: inherit; opacity: 0.88; }}

.vd-progress {{
    --vd-progress-color: var(--vd-color-primary);
    display: block; width: 100%; height: 0.5rem;
    overflow: hidden; border: 0; border-radius: {r}full);
    background: var(--vd-color-surface-raised); appearance: none;
}}
.vd-progress::-webkit-progress-bar {{
    background: var(--vd-color-surface-raised); border-radius: inherit;
}}
.vd-progress::-webkit-progress-value {{
    background: var(--vd-progress-color); border-radius: inherit;
    transition: width {m}slow) ease;
}}
.vd-progress::-moz-progress-bar {{
    background: var(--vd-progress-color); border-radius: inherit;
}}
.vd-progress:not([value]) {{ animation: vd-pulse 1.4s ease-in-out infinite; }}
.vd-progress--primary {{ --vd-progress-color: var(--vd-color-primary); }}
.vd-progress--info {{ --vd-progress-color: var(--vd-color-info); }}
.vd-progress--success {{ --vd-progress-color: var(--vd-color-success); }}
.vd-progress--warning {{ --vd-progress-color: var(--vd-color-warning); }}
.vd-progress--danger {{ --vd-progress-color: var(--vd-color-danger); }}
.vd-progress--sm {{ height: 0.25rem; }}
.vd-progress--lg {{ height: 0.75rem; }}

.vd-spinner {{
    display: inline-flex; align-items: center; justify-content: center;
    vertical-align: middle;
}}
.vd-spinner-glyph {{
    width: 1.125rem; height: 1.125rem; border-radius: 50%;
    border: 2px solid color-mix(in srgb, currentColor 20%, transparent);
    border-top-color: currentColor; animation: vd-spin 700ms linear infinite;
}}
.vd-spinner--sm .vd-spinner-glyph {{ width: 0.875rem; height: 0.875rem; }}
.vd-spinner--lg .vd-spinner-glyph {{ width: 1.5rem; height: 1.5rem; border-width: 2.5px; }}

/* Navigation and grouping */
.vd-breadcrumb {{ min-width: 0; }}
.vd-breadcrumb-list {{
    display: flex; align-items: center; flex-wrap: wrap; gap: 0.4rem;
    list-style: none; color: var(--vd-color-text-muted); font-size: {t}sm);
}}
.vd-breadcrumb-item {{ display: inline-flex; align-items: center; gap: 0.4rem; }}
.vd-breadcrumb-item:not(:last-child)::after {{
    content: "/"; color: var(--vd-color-text-muted); opacity: 0.65; user-select: none;
}}
.vd-breadcrumb-link {{
    color: inherit; text-decoration: none; transition: color {m}fast);
}}
.vd-breadcrumb-link:hover {{ color: var(--vd-color-text); text-decoration: none; }}
.vd-breadcrumb-current {{ color: var(--vd-color-text); font-weight: var(--vd-weight-medium); }}

.vd-button-group {{ display: inline-flex; align-items: stretch; }}
.vd-button-group--vertical {{ flex-direction: column; }}
.vd-button-group:not(.vd-button-group--attached) {{ gap: {s}sm); }}
.vd-button-group--attached > .vd-button {{ position: relative; border-radius: 0; }}
.vd-button-group--attached > .vd-button:hover,
.vd-button-group--attached > .vd-button:focus-visible {{ z-index: 1; }}
.vd-button-group--horizontal.vd-button-group--attached > .vd-button + .vd-button {{
    margin-left: -1px;
}}
.vd-button-group--horizontal.vd-button-group--attached > .vd-button:first-child {{
    border-radius: {r}md) 0 0 {r}md);
}}
.vd-button-group--horizontal.vd-button-group--attached > .vd-button:last-child {{
    border-radius: 0 {r}md) {r}md) 0;
}}
.vd-button-group--vertical.vd-button-group--attached > .vd-button + .vd-button {{
    margin-top: -1px;
}}
.vd-button-group--vertical.vd-button-group--attached > .vd-button:first-child {{
    border-radius: {r}md) {r}md) 0 0;
}}
.vd-button-group--vertical.vd-button-group--attached > .vd-button:last-child {{
    border-radius: 0 0 {r}md) {r}md);
}}

/* Disclosure and content helpers */
.vd-accordion {{ display: grid; gap: {s}sm); }}
.vd-accordion--contained {{
    gap: 0; border: 1px solid var(--vd-color-border);
    border-radius: {r}lg); overflow: hidden;
}}
.vd-accordion-item {{
    border: 1px solid var(--vd-color-border); border-radius: {r}lg);
    background: var(--vd-color-surface);
}}
.vd-accordion--contained > .vd-accordion-item {{ border: 0; border-radius: 0; }}
.vd-accordion--contained > .vd-accordion-item + .vd-accordion-item {{
    border-top: 1px solid var(--vd-color-border);
}}
.vd-accordion--ghost > .vd-accordion-item {{
    border-color: transparent; background: transparent;
}}
.vd-accordion-summary {{
    display: flex; align-items: center; justify-content: space-between;
    gap: {s}md); padding: {s}md) {s}lg); cursor: pointer;
    font-size: {t}sm); font-weight: var(--vd-weight-medium); list-style: none;
}}
.vd-accordion-summary::-webkit-details-marker {{ display: none; }}
.vd-accordion-summary::after {{
    content: "+"; color: var(--vd-color-text-muted); font-size: 1.15em;
    transition: transform {m}normal);
}}
.vd-accordion-item[open] > .vd-accordion-summary::after {{ transform: rotate(45deg); }}
.vd-accordion-content {{
    padding: 0 {s}lg) {s}lg); color: var(--vd-color-text-muted);
    font-size: {t}sm); line-height: 1.65;
}}
.vd-kbd {{
    display: inline-flex; align-items: center; justify-content: center;
    min-width: 1.5rem; min-height: 1.5rem; padding: 0 0.4rem;
    border: 1px solid var(--vd-color-border); border-bottom-width: 2px;
    border-radius: {r}sm); background: var(--vd-color-surface-raised);
    color: var(--vd-color-text); font-family: var(--vd-font-mono);
    font-size: {t}xs); line-height: 1; box-shadow: {sh}sm);
}}
.vd-aspect-ratio {{ position: relative; width: 100%; overflow: hidden; }}
.vd-aspect-ratio > * {{ width: 100%; height: 100%; object-fit: cover; }}
.vd-visually-hidden {{
    position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;
    overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0;
}}

/* Divider */
.vd-divider {{
    margin: 0; height: 1px; width: 100%; border: none;
    background: var(--vd-color-border);
}}

/* Dialog */
.vd-dialog {{
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    border-radius: {r}xl); box-shadow: {sh}lg); color: var(--vd-color-text);
}}
.vd-dialog::backdrop {{ background: rgb(0 0 0 / 0.5); }}

/* Modal */
.vd-modal {{
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    border-radius: {r}xl); box-shadow: {sh}lg);
    padding: {s}xl); width: 100%; max-width: 32rem;
    margin: auto; display: flex; flex-direction: column; gap: {s}md);
    color: var(--vd-color-text);
}}
.vd-modal::backdrop {{ background: rgb(0 0 0 / 0.6); }}

/* Link */
.vd-link {{
    color: var(--vd-color-secondary); text-decoration: none;
    text-underline-offset: 4px; cursor: pointer;
    transition: color {m}normal);
}}
.vd-link:hover {{ text-decoration: underline; }}

/* List */
.vd-list {{ list-style: none; padding-left: 0; margin: 0; }}
.vd-list--ordered {{ list-style: decimal; padding-left: 1.5rem; }}
.vd-list--unstyled {{ list-style: none; padding-left: 0; }}
.vd-list-item {{ padding: {s}xs) 0; color: var(--vd-color-text); }}

/* ChatBox */
.vd-chatbox {{
    display: flex; flex-direction: column; gap: {s}sm);
    overflow-y: auto;
}}

/* Icon (inline SVG sizing + alignment) */
.vd-icon {{
    display: inline-block; vertical-align: middle; flex-shrink: 0;
}}

/* Message list (chat transcript) */
.vd-message-list {{
    display: flex; flex-direction: column; gap: {s}md);
    overflow-y: auto; padding: {s}md);
    flex: 1; min-height: 0;
}}

/* Chat message bubbles */
.vd-chat-message {{
    display: flex; flex-direction: column; max-width: 80%;
    padding: {s}sm) {s}md); border-radius: {r}lg);
    font-size: {t}sm); line-height: 1.6; color: var(--vd-color-text);
    white-space: pre-wrap; word-break: break-word;
}}
.vd-chat-message--user {{
    align-self: flex-end;
    background: var(--vd-color-primary); color: var(--vd-color-primary-contrast, #fff);
    border-bottom-right-radius: {r}sm);
}}
.vd-chat-message--assistant {{
    align-self: flex-start;
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-bottom-left-radius: {r}sm);
}}
.vd-chat-message--system {{
    align-self: center; font-size: {t}xs); color: var(--vd-color-text-muted);
    background: transparent;
}}
.vd-chat-message--tool {{
    align-self: flex-start; font-size: {t}xs);
    background: var(--vd-color-surface); border: 1px dashed var(--vd-color-border);
    color: var(--vd-color-text-muted); font-family: var(--vd-font-mono, monospace);
}}
.vd-chat-message pre, .vd-chat-message code {{
    font-family: var(--vd-font-mono, monospace); font-size: {t}xs);
}}
.vd-chat-message pre {{
    background: rgb(0 0 0 / 0.25); padding: {s}sm); border-radius: {r}md);
    overflow-x: auto; white-space: pre; margin: {s}xs) 0;
}}

/* Streaming text + caret */
.vd-streaming-text {{
    white-space: pre-wrap; word-break: break-word; color: var(--vd-color-text);
}}
.vd-caret {{
    display: inline-block; width: 0.5em; height: 1em; margin-left: 2px;
    vertical-align: text-bottom; background: var(--vd-color-primary);
    animation: vd-blink 1s steps(2) infinite;
}}
@keyframes vd-blink {{ 50% {{ opacity: 0; }} }}

/* Composer (chat input bar) */
.vd-composer {{
    display: flex; align-items: flex-end; gap: {s}sm);
    padding: {s}sm); border: 1px solid var(--vd-color-border);
    border-radius: {r}lg); background: var(--vd-color-surface);
}}
.vd-composer-input {{
    flex: 1; resize: none; border: none; outline: none; background: transparent;
    color: var(--vd-color-text); font-size: {t}sm); line-height: 1.5;
    font-family: inherit; padding: {s}xs) {s}sm);
    max-height: 200px;
}}
.vd-composer-input:focus {{ box-shadow: none; }}
.vd-composer-send {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 2.25rem; height: 2.25rem; border: none; cursor: pointer;
    border-radius: {r}md); background: var(--vd-color-primary);
    color: var(--vd-color-primary-contrast, #fff);
    transition: opacity {m}normal);
}}
.vd-composer-send:hover {{ opacity: 0.9; }}
.vd-composer-send:disabled {{ opacity: 0.5; cursor: not-allowed; }}

/* Sidebar shell */
.vd-sidebar {{
    position: relative; display: flex; flex-direction: column; gap: {s}sm);
    width: 16rem; padding: {s}md); flex-shrink: 0;
    border-right: 1px solid var(--vd-color-border);
    background: var(--vd-color-surface); color: var(--vd-color-text);
    overflow-x: hidden; overflow-y: auto;
    transition: width {m}slow) ease, padding {m}slow) ease,
        transform {m}slow) ease, opacity {m}normal) ease, visibility 0s;
}}
.vd-sidebar--expanded, .vd-sidebar--rail,
.vd-sidebar[data-vd-sidebar-mode="expanded"],
.vd-sidebar[data-vd-sidebar-mode="rail"] {{ visibility: visible; }}
.vd-sidebar--rail, .vd-sidebar[data-vd-sidebar-mode="rail"] {{
    width: 4.5rem; padding-inline: {s}sm); padding-bottom: 4rem;
}}
.vd-sidebar--rail [data-vd-sidebar-label],
.vd-sidebar[data-vd-sidebar-mode="rail"] [data-vd-sidebar-label] {{
    width: 0; opacity: 0; overflow: hidden; pointer-events: none;
}}
.vd-sidebar--hidden, .vd-sidebar[data-vd-sidebar-mode="hidden"] {{
    width: 0; min-width: 0; padding-inline: 0; border-inline-width: 0;
    opacity: 0; transform: translateX(-100%); pointer-events: none;
    visibility: hidden; transition-delay: 0s, 0s, 0s, 0s, {m}slow);
}}
.vd-sidebar-heading {{
    font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    text-transform: uppercase; letter-spacing: 0.08em;
    color: var(--vd-color-text-muted); padding: 0 {s}xs);
}}
.vd-sidebar-item {{
    display: flex; align-items: center; gap: {s}sm); width: 100%;
    min-height: 2.5rem; padding: {s}sm); border: 0; border-radius: {r}md);
    background: transparent; color: var(--vd-color-text-muted);
    font-size: {t}sm); text-decoration: none; cursor: pointer;
    transition: color {m}fast), background {m}fast);
}}
.vd-sidebar-item:hover {{ background: var(--vd-color-surface-raised); color: var(--vd-color-text); }}
.vd-sidebar-item:disabled, .vd-sidebar-item[aria-disabled="true"] {{
    opacity: 0.45; cursor: not-allowed; pointer-events: none;
}}
.vd-sidebar-item--active {{
    background: var(--vd-color-secondary-soft); color: var(--vd-color-secondary);
}}
.vd-sidebar-item-icon {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 1.5rem; height: 1.5rem; flex: 0 0 1.5rem;
}}
.vd-sidebar-item-label {{
    min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    transition: opacity {m}fast), width {m}slow);
}}
.vd-sidebar-item-badge {{
    margin-left: auto; font-size: {t}xs); color: var(--vd-color-text-muted);
}}
.vd-sidebar--rail .vd-sidebar-item,
.vd-sidebar[data-vd-sidebar-mode="rail"] .vd-sidebar-item {{
    justify-content: center; gap: 0;
}}
.vd-sidebar-header {{
    display: flex; align-items: center; justify-content: space-between;
    gap: {s}sm); min-height: 2.5rem; flex: 0 0 auto;
}}
.vd-sidebar-brand {{
    display: flex; align-items: center; gap: {s}sm);
    min-width: 0; color: var(--vd-color-text); text-decoration: none;
}}
.vd-sidebar-brand-mark {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 2rem; height: 2rem; flex: 0 0 2rem;
    border: 1px solid var(--vd-color-border); border-radius: {r}md);
    background: var(--vd-color-surface-raised);
    font-size: {t}sm); font-weight: var(--vd-weight-bold);
    letter-spacing: -0.03em;
}}
.vd-sidebar-brand-text {{
    min-width: 0; overflow: hidden; text-overflow: ellipsis;
    white-space: nowrap; font-size: {t}sm);
    font-weight: var(--vd-weight-semibold); letter-spacing: -0.01em;
}}
.vd-sidebar-controls {{
    display: flex; align-items: center; justify-content: flex-end;
    min-height: 2.5rem; flex: 0 0 auto;
}}
.vd-sidebar--rail .vd-sidebar-header,
.vd-sidebar[data-vd-sidebar-mode="rail"] .vd-sidebar-header {{
    flex-direction: column; justify-content: flex-start;
}}
.vd-sidebar--rail .vd-sidebar-brand,
.vd-sidebar[data-vd-sidebar-mode="rail"] .vd-sidebar-brand {{
    justify-content: center; gap: 0;
}}
.vd-sidebar--rail .vd-sidebar-controls,
.vd-sidebar[data-vd-sidebar-mode="rail"] .vd-sidebar-controls {{
    position: absolute; inset: auto {s}sm) {s}md);
    justify-content: center; gap: 0;
}}
.vd-sidebar-toggle {{
    position: relative; z-index: 95;
    display: inline-flex; align-items: center; justify-content: center;
    width: 2.5rem; height: 2.5rem; padding: 0; border-radius: {r}md);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    color: var(--vd-color-text-muted); cursor: pointer;
}}
.vd-sidebar-toggle:hover {{ background: var(--vd-color-surface-raised); color: var(--vd-color-text); }}
.vd-sidebar-toggle--inside {{ flex: 0 0 auto; }}
.vd-sidebar--rail .vd-sidebar-toggle--inside,
.vd-sidebar[data-vd-sidebar-mode="rail"] .vd-sidebar-toggle--inside {{
    border-color: transparent; background: transparent;
}}
.vd-sidebar-toggle--launcher {{
    display: none; position: fixed; z-index: 95;
    inset: max({s}md), env(safe-area-inset-top)) auto auto
        max({s}md), env(safe-area-inset-left));
    box-shadow: {sh}sm);
}}
.vd-sidebar-toggle--launcher[data-vd-sidebar-current-mode="hidden"] {{
    display: inline-flex;
}}
.vd-sidebar-toggle-glyph {{
    position: relative; width: 1rem; height: 0.75rem;
    border-top: 1.5px solid currentColor; border-bottom: 1.5px solid currentColor;
}}
.vd-sidebar-toggle-glyph::after {{
    content: ""; position: absolute; inset: 50% 0 auto; border-top: 1.5px solid currentColor;
}}
.vd-sidebar-toggle--inside .vd-sidebar-toggle-glyph {{
    width: 0.5rem; height: 0.5rem;
    border: solid currentColor; border-width: 0 1.5px 1.5px 0;
    transform: rotate(135deg);
    transition: transform {m}fast);
}}
.vd-sidebar-toggle--inside .vd-sidebar-toggle-glyph::after {{ display: none; }}
.vd-sidebar-toggle--inside[data-vd-sidebar-current-mode="rail"]
    .vd-sidebar-toggle-glyph {{
    transform: rotate(-45deg);
}}
.vd-sidebar-scrim {{
    position: fixed; inset: 0; z-index: 89; padding: 0; border: 0;
    background: rgb(0 0 0 / 0.42); backdrop-filter: blur(1px);
    animation: vd-overlay-in {m}normal) ease both;
}}

/* Interactive overlays */
.vd-drawer-shell, .vd-dropdown-shell {{ display: contents; }}
.vd-drawer {{
    width: min(24rem, calc(100vw - 1rem)); max-width: none;
    height: 100dvh; max-height: none; margin: 0; padding: 0;
    border: 0; background: var(--vd-color-surface); color: var(--vd-color-text);
    box-shadow: {sh}xl); overflow: hidden;
}}
.vd-drawer::backdrop {{
    background: rgb(0 0 0 / 0.52); backdrop-filter: blur(2px);
    animation: vd-overlay-in {m}normal) ease both;
}}
.vd-drawer[open] {{ display: flex; flex-direction: column; animation: vd-drawer-in {m}slow) ease both; }}
.vd-drawer[data-vd-closing] {{ animation: vd-drawer-out {m}normal) ease both; }}
.vd-drawer--left {{ inset: 0 auto 0 0; }}
.vd-drawer--right {{ inset: 0 0 0 auto; }}
.vd-drawer--right[open] {{ animation-name: vd-drawer-right-in; }}
.vd-drawer--right[data-vd-closing] {{ animation-name: vd-drawer-right-out; }}
.vd-drawer--top {{
    inset: 0 0 auto; width: 100vw; height: min(28rem, calc(100dvh - 1rem));
}}
.vd-drawer--top[open] {{ animation-name: vd-drawer-top-in; }}
.vd-drawer--top[data-vd-closing] {{ animation-name: vd-drawer-top-out; }}
.vd-drawer--bottom {{
    inset: auto 0 0; width: 100vw; height: min(28rem, calc(100dvh - 1rem));
    border-radius: {r}xl) {r}xl) 0 0;
}}
.vd-drawer--bottom[open] {{ animation-name: vd-drawer-bottom-in; }}
.vd-drawer--bottom[data-vd-closing] {{ animation-name: vd-drawer-bottom-out; }}
.vd-drawer--left.vd-drawer--sm, .vd-drawer--right.vd-drawer--sm {{
    width: min(20rem, calc(100vw - 1rem));
}}
.vd-drawer--left.vd-drawer--lg, .vd-drawer--right.vd-drawer--lg {{
    width: min(32rem, calc(100vw - 1rem));
}}
.vd-drawer--top.vd-drawer--sm, .vd-drawer--bottom.vd-drawer--sm {{
    height: min(16rem, calc(100dvh - 1rem));
}}
.vd-drawer--top.vd-drawer--lg, .vd-drawer--bottom.vd-drawer--lg {{
    height: min(36rem, calc(100dvh - 1rem));
}}
.vd-drawer--full {{ width: 100vw; height: 100dvh; }}
.vd-drawer-header {{
    display: grid; grid-template-columns: 1fr auto; gap: {s}xs) {s}md);
    align-items: center; padding: {s}lg); border-bottom: 1px solid var(--vd-color-border);
}}
.vd-drawer-title {{ font-size: {t}lg); font-weight: var(--vd-weight-semibold); }}
.vd-drawer-description {{ color: var(--vd-color-text-muted); font-size: {t}sm); }}
.vd-drawer-header > .vd-button {{ grid-column: 2; grid-row: 1 / span 2; }}
.vd-drawer-body {{ flex: 1; min-height: 0; padding: {s}lg); overflow-y: auto; }}

.vd-dropdown-menu {{
    position: fixed; inset: auto; left: var(--vd-anchor-x, 0);
    top: var(--vd-anchor-y, 0); z-index: 100; min-width: 12rem;
    max-width: min(22rem, calc(100vw - 1rem)); margin: 0; padding: {s}xs);
    border: 1px solid var(--vd-color-border); border-radius: {r}lg);
    background: var(--vd-color-surface); color: var(--vd-color-text);
    box-shadow: {sh}lg); opacity: 0; transform: translateY(-0.25rem) scale(0.98);
}}
.vd-dropdown-menu:popover-open,
.vd-dropdown-menu[data-vd-fallback-open] {{
    opacity: 1; transform: translateY(0) scale(1);
    transition: opacity {m}fast), transform {m}fast);
}}
.vd-menu-item {{
    display: flex; align-items: center; justify-content: space-between; gap: {s}lg);
    width: 100%; min-height: 2.25rem; padding: {s}sm);
    border: 0; border-radius: {r}md); background: transparent;
    color: var(--vd-color-text); font-size: {t}sm); text-decoration: none;
    text-align: left; cursor: pointer;
}}
.vd-menu-item:hover, .vd-menu-item:focus-visible {{
    background: var(--vd-color-surface-raised); outline: none;
}}
.vd-menu-item--destructive {{ color: var(--vd-color-danger); }}
.vd-menu-item:disabled {{ opacity: 0.45; cursor: not-allowed; }}
.vd-menu-shortcut {{ margin-left: auto; color: var(--vd-color-text-muted); font-size: {t}xs); }}
.vd-menu-separator {{ height: 1px; margin: {s}xs) 0; border: 0; background: var(--vd-color-border); }}

/* Tabs */
.vd-tabs {{ display: flex; flex-direction: column; min-width: 0; }}
.vd-tabs--vertical {{ flex-direction: row; gap: {s}lg); }}
.vd-tabs-list {{
    display: flex; align-items: center; gap: {s}xs);
    border-bottom: 1px solid var(--vd-color-border);
}}
.vd-tabs--vertical > .vd-tabs-list {{
    flex-direction: column; align-items: stretch; border-bottom: 0;
    border-right: 1px solid var(--vd-color-border);
}}
.vd-tabs--vertical .vd-tabs-trigger::after {{
    inset: {s}sm) -1px {s}sm) auto; width: 2px; height: auto;
}}
.vd-tabs-trigger {{
    position: relative; min-height: 2.5rem; padding: {s}sm) {s}md);
    border: 0; background: transparent; color: var(--vd-color-text-muted);
    font-size: {t}sm); font-weight: var(--vd-weight-medium); cursor: pointer;
}}
.vd-tabs-trigger::after {{
    content: ""; position: absolute; inset: auto {s}md) -1px;
    height: 2px; border-radius: {r}full); background: transparent;
}}
.vd-tabs-trigger[aria-selected="true"] {{ color: var(--vd-color-text); }}
.vd-tabs-trigger[aria-selected="true"]::after {{ background: var(--vd-color-secondary); }}
.vd-tabs-trigger:disabled {{ opacity: 0.45; cursor: not-allowed; }}
.vd-tabs-panel {{ padding-block: {s}lg); min-width: 0; }}

/* Toasts and snackbars */
.vd-toast-region {{
    position: fixed; z-index: 120; display: flex; flex-direction: column;
    gap: {s}sm); width: min(24rem, calc(100vw - 2rem));
    pointer-events: none;
}}
.vd-toast-region--top-left {{ top: max(1rem, env(safe-area-inset-top)); left: max(1rem, env(safe-area-inset-left)); }}
.vd-toast-region--top-right {{ top: max(1rem, env(safe-area-inset-top)); right: max(1rem, env(safe-area-inset-right)); }}
.vd-toast-region--bottom-left {{ bottom: max(1rem, env(safe-area-inset-bottom)); left: max(1rem, env(safe-area-inset-left)); }}
.vd-toast-region--bottom-right {{ bottom: max(1rem, env(safe-area-inset-bottom)); right: max(1rem, env(safe-area-inset-right)); }}
.vd-toast {{
    --vd-toast-accent: var(--vd-color-secondary);
    display: flex; align-items: center; gap: {s}md); width: 100%;
    padding: {s}md); border: 1px solid var(--vd-color-border);
    border-left: 3px solid var(--vd-toast-accent); border-radius: {r}lg);
    background: var(--vd-color-surface-raised); color: var(--vd-color-text);
    box-shadow: {sh}lg); pointer-events: auto;
    animation: vd-toast-in {m}slow) ease both;
}}
.vd-toast[data-vd-closing] {{ animation: vd-toast-out {m}normal) ease both; }}
.vd-toast--info {{ --vd-toast-accent: var(--vd-color-info); }}
.vd-toast--success {{ --vd-toast-accent: var(--vd-color-success); }}
.vd-toast--warning {{ --vd-toast-accent: var(--vd-color-warning); }}
.vd-toast--danger {{ --vd-toast-accent: var(--vd-color-danger); }}
.vd-toast--snackbar {{ border-left-width: 1px; }}
.vd-toast-content {{ min-width: 0; flex: 1; }}
.vd-toast-title {{ font-size: {t}sm); font-weight: var(--vd-weight-semibold); }}
.vd-toast-message {{ color: var(--vd-color-text-muted); font-size: {t}sm); line-height: 1.45; }}
.vd-toast-actions {{ display: flex; align-items: center; gap: {s}xs); }}
.vd-toast-dismiss {{
    min-width: 2rem; min-height: 2rem; padding: 0 {s}sm); border: 0;
    border-radius: {r}sm); background: transparent;
    color: var(--vd-color-text-muted); cursor: pointer;
}}
.vd-toast-dismiss:hover {{ background: var(--vd-color-surface); color: var(--vd-color-text); }}

@keyframes vd-overlay-in {{ from {{ opacity: 0; }} }}
@keyframes vd-drawer-in {{ from {{ opacity: 0; transform: translateX(-1.5rem); }} }}
@keyframes vd-drawer-out {{ to {{ opacity: 0; transform: translateX(-1rem); }} }}
@keyframes vd-drawer-right-in {{ from {{ opacity: 0; transform: translateX(1.5rem); }} }}
@keyframes vd-drawer-right-out {{ to {{ opacity: 0; transform: translateX(1rem); }} }}
@keyframes vd-drawer-top-in {{ from {{ opacity: 0; transform: translateY(-1.5rem); }} }}
@keyframes vd-drawer-top-out {{ to {{ opacity: 0; transform: translateY(-1rem); }} }}
@keyframes vd-drawer-bottom-in {{ from {{ opacity: 0; transform: translateY(1.5rem); }} }}
@keyframes vd-drawer-bottom-out {{ to {{ opacity: 0; transform: translateY(1rem); }} }}
@keyframes vd-toast-in {{
    from {{ opacity: 0; transform: translateY(0.75rem) scale(0.98); }}
}}
@keyframes vd-toast-out {{
    to {{ opacity: 0; transform: translateX(1rem) scale(0.98); }}
}}


.vd-app-shell {{
    display: flex; align-items: stretch;
    width: 100%; height: 100dvh; overflow: hidden;
}}
.vd-app-shell > .vd-sidebar {{
    height: 100dvh; border-right: 1px solid var(--vd-color-border);
}}
.vd-app-shell-content {{
    min-width: 0; min-height: 0; flex: 1;
    overflow: auto; padding: clamp({s}lg), 3vw, {s}xl));
}}
.vd-app-shell-content--pad-none {{ padding: 0; }}
.vd-app-shell-content--pad-sm {{ padding: {s}md); }}
.vd-app-shell-content--pad-md {{
    padding: clamp({s}md), 2vw, {s}lg));
}}
.vd-app-shell-content--pad-xl {{
    padding: clamp({s}xl), 4vw, {s}xxl));
}}
.vd-bottom-nav {{
    display: none; position: fixed; z-index: 80; inset: auto 0 0;
    align-items: stretch; justify-content: space-around;
    min-height: calc(3.75rem + env(safe-area-inset-bottom));
    padding: {s}xs) {s}sm) env(safe-area-inset-bottom);
    border-top: 1px solid var(--vd-color-border);
    background: color-mix(in srgb, var(--vd-color-surface) 92%, transparent);
    backdrop-filter: blur(18px) saturate(140%);
}}
.vd-bottom-nav-item {{
    display: flex; flex: 1; min-width: 0; min-height: 3.25rem;
    flex-direction: column; align-items: center; justify-content: center;
    gap: 0.2rem; border-radius: {r}md); color: var(--vd-color-text-muted);
    font-size: {t}xs); text-decoration: none;
}}
.vd-bottom-nav-item:hover {{ color: var(--vd-color-text); text-decoration: none; }}
.vd-bottom-nav-item--active {{ color: var(--vd-color-secondary); }}
.vd-bottom-nav-item-icon {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 1.5rem; height: 1.5rem;
}}
.vd-bottom-nav-item-label {{
    max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}}
.vd-chat-main {{
    flex: 1; min-width: 0; display: flex; flex-direction: column;
    height: 100dvh; overflow: hidden;
    padding: {s}lg); gap: {s}md);
}}
.vd-chat-scroll {{
    flex: 1; min-height: 0; overflow-y: auto;
    display: flex; flex-direction: column;
    border: 1px solid var(--vd-color-border);
    border-radius: {r}lg); background: var(--vd-color-surface);
    padding: {s}md);
}}
.vd-chat-row {{
    width: 100%; align-items: center;
}}
.vd-chat-row > .vd-button:first-child {{
    flex: 1; justify-content: flex-start; text-align: left;
    overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    background: transparent; color: var(--vd-color-text);
    border: none; font-weight: var(--vd-weight-normal);
}}
.vd-chat-row > .vd-button:first-child:hover {{
    background: var(--vd-color-surface); color: var(--vd-color-primary);
}}
.vd-chat-row > .vd-button:last-child {{
    flex-shrink: 0; background: transparent; border: none;
    color: var(--vd-color-text-muted); padding: {s}xs);
}}
.vd-chat-row > .vd-button:last-child:hover {{ color: var(--vd-color-danger); }}
.vd-suggestions {{
    display: flex; flex-wrap: wrap; gap: {s}sm);
}}
.vd-suggestions > .vd-button {{
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    color: var(--vd-color-text); font-weight: var(--vd-weight-normal);
}}
.vd-suggestions > .vd-button:hover {{
    border-color: var(--vd-color-primary); color: var(--vd-color-primary);
}}

/* Markdown rendered inside components */
.vd-markdown p {{ margin: 0 0 {s}sm); }}
.vd-markdown p:last-child {{ margin-bottom: 0; }}
.vd-markdown h1, .vd-markdown h2, .vd-markdown h3,
.vd-markdown h4, .vd-markdown h5, .vd-markdown h6 {{
    margin: {s}sm) 0 {s}xs); font-weight: var(--vd-weight-semibold);
    color: var(--vd-color-text); line-height: 1.3;
}}
.vd-markdown ul, .vd-markdown ol {{ margin: 0 0 {s}sm); padding-left: 1.25rem; }}
.vd-markdown li {{ margin: {s}xs) 0; }}
.vd-markdown blockquote {{
    margin: 0 0 {s}sm); padding: {s}xs) {s}sm);
    border-left: 3px solid var(--vd-color-border);
    color: var(--vd-color-text-muted);
}}
.vd-markdown code {{
    font-family: var(--vd-font-mono, monospace); font-size: 0.875em;
    background: rgb(0 0 0 / 0.15); padding: 0.125em 0.375em; border-radius: {r}sm);
}}
.vd-markdown pre {{
    margin: 0 0 {s}sm); padding: {s}sm); overflow-x: auto;
    background: rgb(0 0 0 / 0.25); border-radius: {r}md);
}}
.vd-markdown pre code {{ background: transparent; padding: 0; }}
.vd-markdown a {{
    color: var(--vd-color-secondary); text-underline-offset: 4px;
}}

/* Semantic structure */
.vd-nav {{
    display: flex; align-items: center; gap: {s}md);
    padding: {s}md) {s}lg); border-bottom: 1px solid var(--vd-color-border);
    background: var(--vd-color-background);
}}
.vd-header {{
    display: flex; align-items: center; justify-content: space-between;
    padding: {s}md) {s}lg); border-bottom: 1px solid var(--vd-color-border);
    background: var(--vd-color-background);
}}
.vd-footer {{
    padding: {s}lg); border-top: 1px solid var(--vd-color-border);
    color: var(--vd-color-text-muted); font-size: {t}sm);
    background: var(--vd-color-background);
}}
.vd-main {{ flex: 1; }}
.vd-section {{ padding: {s}xl) 0; }}
.vd-article {{ max-width: 65ch; }}
.vd-aside {{ color: var(--vd-color-text-muted); font-size: {t}sm); }}
.vd-figure {{ margin: 0; }}
.vd-figcaption {{
    font-size: {t}sm); color: var(--vd-color-text-muted); margin-top: {s}sm);
}}
.vd-address {{ font-style: normal; color: var(--vd-color-text-muted); }}
.vd-time {{ color: var(--vd-color-text-muted); font-size: {t}sm); }}
.vd-img {{ border-radius: {r}md); }}

/* Table */
.vd-table {{ width: 100%; border-collapse: collapse; color: var(--vd-color-text); }}
.vd-table-head {{
    background: var(--vd-color-surface); border-bottom: 1px solid var(--vd-color-border);
}}
.vd-table-row {{
    border-bottom: 1px solid var(--vd-color-border);
    transition: background {m}normal);
}}
.vd-table-row:hover {{ background: var(--vd-color-surface); }}
.vd-table-header-cell {{
    padding: 0.875rem 1.5rem; text-align: left;
    font-size: {t}xs); font-weight: var(--vd-weight-medium);
    color: var(--vd-color-text-muted); text-transform: uppercase;
    letter-spacing: 0.05em;
}}
.vd-table-cell {{
    padding: 0.875rem 1.5rem; white-space: nowrap;
    font-size: {t}sm); color: var(--vd-color-text);
}}

/* User badge */
.vd-user-badge {{
    display: inline-flex; align-items: center; gap: {s}sm);
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-radius: {r}full); padding: 0.25rem 0.75rem 0.25rem 0.25rem;
    color: var(--vd-color-text); font-size: {t}sm); font-weight: var(--vd-weight-medium);
}}
.vd-user-badge-avatar {{
    display: flex; height: 1.75rem; width: 1.75rem; align-items: center;
    justify-content: center; border-radius: {r}full);
    background: var(--vd-color-secondary); color: #fff;
    font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    text-transform: uppercase;
}}
.vd-user-badge-name {{ line-height: 1; font-size: {t}sm); }}
.vd-user-badge-meta {{ font-size: {t}xs); color: var(--vd-color-text-muted); }}

/* Auth guard */
.vd-auth-guard {{
    padding: {s}md); text-align: center; font-size: {t}sm);
    color: var(--vd-color-text-muted);
}}
.vd-auth-guard--error {{ color: var(--vd-color-danger); font-weight: var(--vd-weight-medium); }}

/* Chrome — navbar */
.vd-navbar {{
    position: sticky; top: 0; z-index: 40;
    display: flex; align-items: center; justify-content: space-between;
    flex-wrap: wrap; gap: {s}sm) {s}md);
    padding: {s}md) {s}lg);
    background: color-mix(in srgb, var(--vd-color-background) 82%, transparent);
    backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid var(--vd-color-border-soft);
}}
.vd-navbar--sticky {{ position: sticky; top: 0; }}

/* Chrome — nav link */
.vd-nav-link {{
    color: var(--vd-color-text-muted); text-decoration: none;
    font-size: {t}sm); font-weight: var(--vd-weight-medium);
    padding: 0.375rem 0.625rem; border-radius: {r}md);
    transition: color {m}normal), background {m}normal);
}}
.vd-nav-link:hover {{ color: var(--vd-color-text); background: var(--vd-color-surface); }}
.vd-nav-link--active {{ color: var(--vd-color-primary); }}

/* Chrome — brand */
.vd-brand {{
    font-family: var(--vd-font-display);
    font-size: {t}lg); font-weight: var(--vd-weight-bold);
    color: var(--vd-color-text); text-decoration: none; letter-spacing: -0.02em;
}}

/* Chrome — theme toggle */
.vd-theme-toggle {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 2.25rem; height: 2.25rem; border-radius: {r}full);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    color: var(--vd-color-text); cursor: pointer; font-size: {t}sm);
    transition: background {m}normal), border-color {m}normal);
}}
.vd-theme-toggle:hover {{ background: var(--vd-color-surface-raised); }}
.vd-theme-toggle-sun {{ display: none; }}
.vd-theme-toggle-moon {{ display: inline; }}
.dark .vd-theme-toggle-sun {{ display: inline; }}
.dark .vd-theme-toggle-moon {{ display: none; }}

/* Chrome — eyebrow */
.vd-eyebrow {{
    display: inline-block; font-size: {t}xs);
    font-weight: var(--vd-weight-semibold); letter-spacing: 0.12em;
    text-transform: uppercase; color: var(--vd-color-secondary);
}}

/* Chrome — hero */
.vd-hero {{
    display: grid; gap: {s}xl);
    padding: {s}xxl) 0;
}}

/* Chrome — page hero */
.vd-page-hero {{
    padding: {s}xxl) {s}lg);
    border-bottom: 1px solid var(--vd-color-border);
    background: var(--vd-color-surface);
}}

/* Chrome — chip */
.vd-chip {{
    display: inline-flex; align-items: center; gap: 0.375rem;
    padding: 0.25rem 0.75rem; border-radius: {r}full);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    font-size: {t}xs); font-weight: var(--vd-weight-medium);
    color: var(--vd-color-text-muted);
}}

/* Chrome — code block */
.vd-code-block {{
    background: var(--vd-code-background);
    border: 1px solid var(--vd-code-border);
    border-radius: {r}lg); padding: {s}lg);
    overflow-x: auto; white-space: pre;
    font-family: var(--vd-font-mono);
    font-size: {t}sm); line-height: 1.7; color: var(--vd-code-text);
}}
.vd-code-block code {{ font: inherit; color: inherit; }}

/* Chrome — stats */
.vd-stats {{ display: grid; gap: {s}md); }}
.vd-stats--cols-2 {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
.vd-stats--cols-3 {{ grid-template-columns: repeat(3, minmax(0, 1fr)); }}
.vd-stats--cols-4 {{ grid-template-columns: repeat(4, minmax(0, 1fr)); }}
.vd-stat {{
    display: flex; flex-direction: column; gap: {s}xs);
    padding: {s}lg); border-radius: {r}lg);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
}}
.vd-stat-value {{
    font-family: var(--vd-font-display);
    font-size: {t}xxxl); font-weight: var(--vd-weight-bold);
    color: var(--vd-color-text); letter-spacing: -0.02em;
}}
.vd-stat-label {{ font-size: {t}sm); color: var(--vd-color-text-muted); }}

/* Chrome — CTA band */
.vd-cta-band {{
    padding: {s}xxl) {s}lg); text-align: center;
    background: var(--vd-color-secondary-soft);
    border-top: 1px solid var(--vd-color-secondary-line);
    border-bottom: 1px solid var(--vd-color-secondary-line);
}}

/* Chrome — back link */
.vd-back-link {{
    display: inline-flex; align-items: center; gap: 0.375rem;
    color: var(--vd-color-text-muted); text-decoration: none;
    font-size: {t}sm); font-weight: var(--vd-weight-medium);
    transition: color {m}normal);
}}
.vd-back-link::before {{ content: "\\2190"; }}
.vd-back-link:hover {{ color: var(--vd-color-text); }}

/* Chrome — feature card */
.vd-feature-card {{
    padding: {s}lg); border-radius: {r}xl);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    transition: transform {m}normal), border-color {m}normal), box-shadow {m}normal);
}}
.vd-feature-card:hover {{
    transform: translateY(-2px);
    border-color: var(--vd-color-secondary);
    box-shadow: {sh}lg);
}}

/* Chrome — link arrow */
.vd-link-arrow {{
    display: inline-flex; align-items: center; gap: 0.375rem;
    color: var(--vd-color-secondary); text-decoration: none;
    font-weight: var(--vd-weight-medium); font-size: {t}sm);
}}
.vd-link-arrow::after {{ content: "\\2192"; transition: transform {m}fast); }}
.vd-link-arrow:hover::after {{ transform: translateX(2px); }}

/* Motion */
@keyframes vd-fade-up {{
    from {{ opacity: 0; transform: translateY(12px); }}
    to {{ opacity: 1; transform: translateY(0); }}
}}
@keyframes vd-fade-in {{
    from {{ opacity: 0; }}
    to {{ opacity: 1; }}
}}
@keyframes vd-pulse {{
    0%, 100% {{ opacity: 1; }}
    50% {{ opacity: 0.6; }}
}}
.vd-hero, .vd-page-hero, .vd-cta-band {{
    animation: vd-fade-up {m}slow) ease-out both;
}}

/* Responsive chrome */
@media (max-width: 767px) {{
    .vd-stats--cols-2, .vd-stats--cols-3, .vd-stats--cols-4 {{
        grid-template-columns: 1fr;
    }}
    .vd-navbar {{ justify-content: center; }}
    .vd-sidebar {{
        position: fixed; inset: 0 auto 0 0; z-index: 90; height: 100dvh;
        box-shadow: {sh}xl);
    }}
    .vd-sidebar[data-vd-sidebar-mode="rail"] {{
        position: relative; inset: auto; width: 4.5rem; box-shadow: none;
    }}
    .vd-bottom-nav {{ display: flex; }}
    .vd-app-shell:has(> .vd-bottom-nav) {{
        padding-bottom: calc(3.75rem + env(safe-area-inset-bottom));
    }}
    .vd-toast-region {{
        right: max(0.75rem, env(safe-area-inset-right));
        bottom: max(0.75rem, env(safe-area-inset-bottom));
        left: max(0.75rem, env(safe-area-inset-left));
        width: auto;
    }}
    .vd-tabs--vertical {{ flex-direction: column; }}
    .vd-tabs--vertical > .vd-tabs-list {{
        flex-direction: row; overflow-x: auto; border-right: 0;
        border-bottom: 1px solid var(--vd-color-border);
    }}
}}

/* Respect reduced-motion preferences */
@media (prefers-reduced-motion: reduce) {{
    *, *::before, *::after {{
        animation: none !important;
        transition: none !important;
    }}
}}
""" + _layout_css()


def _layout_css() -> str:
    """Generate the flex/grid/container/page modifier rules."""
    css: list[str] = []

    # Flex
    css.append("/* Flex */")
    css.append(".vd-flex { display: flex; }")
    css.append(".vd-flex--row { flex-direction: row; }")
    css.append(".vd-flex--col { flex-direction: column; }")
    css.append(".vd-flex--row-reverse { flex-direction: row-reverse; }")
    css.append(".vd-flex--col-reverse { flex-direction: column-reverse; }")
    justify = {
        "start": "flex-start",
        "end": "flex-end",
        "center": "center",
        "between": "space-between",
        "around": "space-around",
        "evenly": "space-evenly",
    }
    for name, value in justify.items():
        css.append(f".vd-flex--justify-{name} {{ justify-content: {value}; }}")
    items = {
        "start": "flex-start",
        "end": "flex-end",
        "center": "center",
        "baseline": "baseline",
        "stretch": "stretch",
    }
    for name, value in items.items():
        css.append(f".vd-flex--items-{name} {{ align-items: {value}; }}")
    css.append(".vd-flex--nowrap { flex-wrap: nowrap; }")
    css.append(".vd-flex--wrap { flex-wrap: wrap; }")
    css.append(".vd-flex--wrap-reverse { flex-wrap: wrap-reverse; }")

    # Grid
    css.append("/* Grid */")
    css.append(".vd-grid { display: grid; }")
    for n in range(1, 13):
        css.append(
            f".vd-grid--cols-{n} {{ grid-template-columns: repeat({n}, minmax(0, 1fr)); }}"
        )

    # Gap utilities (shared by flex + grid)
    css.append("/* Gap */")
    for g in _GAP_SCALE:
        if g == "0":
            value = "0"
        elif g.isdigit():
            # Numeric gaps follow Tailwind's 4px base: gap-4 == 1rem.
            value = f"calc(0.25rem * {g})"
        else:
            value = f"var(--vd-space-{g})"
        css.append(f".vd-flex--gap-{g} {{ gap: {value}; }}")
        css.append(f".vd-grid--gap-{g} {{ gap: {value}; }}")

    # Container
    css.append("/* Container */")
    css.append(".vd-container { width: 100%; margin-left: auto; margin-right: auto; }")
    css.append(".vd-container--centered { margin-left: auto; margin-right: auto; }")
    for name, value in _CONTAINER_SIZES.items():
        css.append(f".vd-container--{name} {{ max-width: {value}; }}")

    # Page
    css.append("/* Page */")
    css.append(
        ".vd-page { width: 100%; flex: 1; margin-left: auto; margin-right: auto; }"
    )
    css.append(".vd-page--pad { padding: var(--vd-space-xl) var(--vd-space-md); }")
    for name, value in _CONTAINER_SIZES.items():
        css.append(f".vd-page--{name} {{ max-width: {value}; }}")

    return "\n".join(css) + "\n"
