"""The native Voodoo CSS adapter.

Returns semantic class names (``vd-button``, ``vd-button--primary``). The
matching CSS is generated by :func:`generate_component_css` and included in
``render_page``. All values reference ``--vd-*`` tokens, so changing the
theme at runtime changes every component without re-rendering.

This is the default adapter. Tailwind is opt-in::

    from voodoo import TailwindAdapter, set_style_adapter
    set_style_adapter(TailwindAdapter())
"""

from __future__ import annotations

from typing import Any

from voodoo.ui.styles.theme import Theme


class VoodooCSSAdapter:
    """Returns semantic ``vd-*`` class names resolved by generated CSS."""

    def component_classes(
        self, component: str, props: dict[str, Any], theme: Theme
    ) -> str:
        # Build BEM-style class names from the semantic key + props
        base = component.replace(".", "-")
        classes: list[str] = [f"vd-{base}"]

        variant = props.get("variant")
        if variant:
            classes.append(f"vd-{base}--{variant}")

        # Heading level
        level = props.get("level")
        if level and component == "heading":
            classes.append(f"vd-{base}--h{level}")

        # Chat message role (user | assistant | system | tool)
        role = props.get("role")
        if role and component == "chat-message":
            classes.append(f"vd-{base}--{role}")

        # Streaming text terminal state (caret hidden when done)
        if component == "streaming-text" and props.get("done"):
            classes.append(f"vd-{base}--done")

        # Size — button/input use it directly
        if component in ("button", "input"):
            size = props.get("size")
            if size and size != "md":
                classes.append(f"vd-{base}--{size}")

        classes.extend(self._layout_classes(component, props))
        return " ".join(classes)

    def _layout_classes(self, component: str, props: dict[str, Any]) -> list[str]:
        """Layout modifier classes (Flex/Grid/Container/Page/List)."""
        classes: list[str] = []

        if component == "flex":
            classes.extend(self._flex_classes(props))

        if component == "grid":
            classes.append(f"vd-grid--cols-{props.get('cols', '1')}")
            classes.append(f"vd-grid--gap-{props.get('gap', '4')}")

        if component == "container":
            classes.append(f"vd-container--{props.get('size', 'xl')}")
            if props.get("centered", True):
                classes.append("vd-container--centered")

        if component == "page":
            classes.append(f"vd-page--{props.get('size', 'lg')}")
            if props.get("pad", True):
                classes.append("vd-page--pad")

        if component == "list":
            classes.extend(self._list_classes(props))

        classes.extend(self._chrome_classes(component, props))
        return classes

    @staticmethod
    def _chrome_classes(component: str, props: dict[str, Any]) -> list[str]:
        """Modifier classes for page-level chrome components."""
        if component == "navbar" and props.get("sticky", True):
            return ["vd-navbar--sticky"]
        if component == "nav-link" and props.get("active"):
            return ["vd-nav-link--active"]
        if component == "stats":
            return [f"vd-stats--cols-{props.get('cols', '3')}"]
        return []

    @staticmethod
    def _flex_classes(props: dict[str, Any]) -> list[str]:
        direction = props.get("direction", "row")
        justify = props.get("justify", "start")
        items = props.get("items", "stretch")
        wrap = props.get("wrap", "nowrap")
        return [
            _FLEX_DIRECTIONS.get(direction, "vd-flex--row"),
            f"vd-flex--justify-{justify if justify in _FLEX_JUSTIFY else 'start'}",
            f"vd-flex--items-{items if items in _FLEX_ITEMS else 'stretch'}",
            f"vd-flex--{wrap if wrap in _FLEX_WRAP else 'nowrap'}",
            f"vd-flex--gap-{props.get('gap', '0')}",
        ]

    @staticmethod
    def _list_classes(props: dict[str, Any]) -> list[str]:
        if props.get("unstyled"):
            return ["vd-list--unstyled"]
        if props.get("ordered"):
            return ["vd-list--ordered"]
        return []


# Layout modifier vocabularies shared by the adapter and the generated CSS
_FLEX_DIRECTIONS = {
    "row": "vd-flex--row",
    "col": "vd-flex--col",
    "row-reverse": "vd-flex--row-reverse",
    "col-reverse": "vd-flex--col-reverse",
}
_FLEX_JUSTIFY = {"start", "end", "center", "between", "around", "evenly"}
_FLEX_ITEMS = {"start", "end", "center", "baseline", "stretch"}
_FLEX_WRAP = {"nowrap", "wrap", "wrap-reverse"}
_GAP_SCALE = [
    "0",
    "xs",
    "sm",
    "md",
    "lg",
    "xl",
    "xxl",
    "xxxl",
] + [str(i) for i in range(1, 13)]
_CONTAINER_SIZES = {
    "sm": "40rem",
    "md": "48rem",
    "lg": "64rem",
    "xl": "80rem",
    "2xl": "96rem",
    "full": "100%",
}


# ---------------------------------------------------------------------------
# CSS generation — produces the stylesheet for all vd-* classes
# ---------------------------------------------------------------------------


def generate_component_css(theme: Theme) -> str:
    """Generate CSS for all ``vd-*`` component classes.

    Uses ``--vd-*`` tokens exclusively so theme changes propagate instantly.
    Includes a base reset, a type scale, full component coverage, and layout
    modifier classes matching :class:`VoodooCSSAdapter`.
    """
    r = "var(--vd-radius-"
    s = "var(--vd-space-"
    t = "var(--vd-text-"
    sh = "var(--vd-shadow-"
    m = "var(--vd-motion-"

    return f"""
/* ── Voodoo Component CSS (generated) ─────────────────────────────── */

/* Base reset */
*, *::before, *::after {{
    box-sizing: border-box; margin: 0; padding: 0;
}}
html {{ -webkit-text-size-adjust: 100%; text-size-adjust: 100%; }}
body {{
    font-family: var(--vd-font-sans); font-size: {t}md);
    line-height: var(--vd-leading-normal); color: var(--vd-color-text);
    background: var(--vd-color-background); min-height: 100vh;
    -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
}}
img, svg, video, canvas {{ display: block; max-width: 100%; }}
button, input, select, textarea {{ font: inherit; color: inherit; }}
:focus-visible {{ outline: 2px solid var(--vd-color-secondary); outline-offset: 2px; }}
::selection {{ background: var(--vd-color-secondary); color: var(--vd-color-on-secondary); }}

/* Typography */
.vd-paragraph {{
    font-size: {t}md); line-height: var(--vd-leading-normal);
    color: var(--vd-color-text-muted); max-width: 65ch;
}}
.vd-text {{ color: var(--vd-color-text); }}
.vd-text--muted {{ color: var(--vd-color-text-muted); }}
.vd-text--primary {{ color: var(--vd-color-primary); }}
.vd-text--success {{ color: var(--vd-color-success); }}
.vd-text--warning {{ color: var(--vd-color-warning); }}
.vd-text--danger {{ color: var(--vd-color-danger); }}

/* Button */
.vd-button {{
    display: inline-flex; align-items: center; justify-content: center;
    gap: {s}sm); white-space: nowrap;
    border-radius: {r}md); font-size: {t}sm); font-weight: var(--vd-weight-medium);
    transition: background {m}normal), color {m}normal), border-color {m}normal),
        box-shadow {m}normal), opacity {m}normal), transform {m}fast);
    border: 1px solid var(--vd-color-border); cursor: pointer; outline: none;
    background: var(--vd-color-surface); color: var(--vd-color-text);
    height: 2.25rem; padding: 0 1rem;
}}
.vd-button:hover {{ background: var(--vd-color-surface-raised); }}
.vd-button:active {{ transform: translateY(1px); }}
.vd-button:focus-visible {{ box-shadow: 0 0 0 2px var(--vd-color-secondary); }}
.vd-button:disabled {{ pointer-events: none; opacity: 0.5; }}
.vd-button--primary {{
    background: var(--vd-color-primary); color: var(--vd-color-on-primary);
}}
.vd-button--primary:hover {{ background: var(--vd-color-primary-hover); }}
.vd-button--secondary {{
    background: var(--vd-color-secondary); color: var(--vd-color-on-secondary);
}}
.vd-button--secondary:hover {{ opacity: 0.9; }}
.vd-button--outline {{
    border: 1px solid var(--vd-color-border); background: transparent;
    color: var(--vd-color-text);
}}
.vd-button--outline:hover {{ background: var(--vd-color-surface); }}
.vd-button--ghost {{
    background: transparent; color: var(--vd-color-text-muted);
}}
.vd-button--ghost:hover {{
    background: var(--vd-color-surface); color: var(--vd-color-text);
}}
.vd-button--danger {{
    background: var(--vd-color-danger); color: #fff;
}}
.vd-button--danger:hover {{ opacity: 0.9; }}
.vd-button--sm {{ height: 2rem; padding: 0 0.75rem; font-size: {t}xs); }}
.vd-button--lg {{ height: 2.5rem; padding: 0 1.5rem; font-size: {t}md); }}

/* Card */
.vd-card {{
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-radius: {r}xl); padding: {s}xl);
    box-shadow: {sh}sm);
}}

/* Form */
.vd-form {{ display: flex; flex-direction: column; gap: {s}md); }}

/* Label */
.vd-label {{
    display: block; font-size: {t}sm); font-weight: var(--vd-weight-medium);
    line-height: 1; color: var(--vd-color-text);
}}

/* Input */
.vd-input {{
    display: flex; width: 100%; height: 2.25rem;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.25rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    transition: border-color {m}normal), box-shadow {m}normal);
}}
.vd-input::placeholder {{ color: var(--vd-color-text-muted); }}
.vd-input:focus-visible {{
    outline: none; border-color: var(--vd-color-secondary);
    box-shadow: 0 0 0 1px var(--vd-color-secondary);
}}
.vd-input:disabled {{ opacity: 0.5; cursor: not-allowed; }}
.vd-input--sm {{ height: 2rem; padding: 0.25rem 0.625rem; }}
.vd-input--lg {{ height: 2.75rem; padding: 0.5rem 1rem; }}

/* Textarea */
.vd-textarea {{
    display: flex; min-height: 80px; width: 100%;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.5rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    transition: border-color {m}normal);
}}
.vd-textarea:focus-visible {{
    outline: none; border-color: var(--vd-color-secondary);
    box-shadow: 0 0 0 1px var(--vd-color-secondary);
}}

/* Select */
.vd-select {{
    display: flex; width: 100%; height: 2.25rem; align-items: center;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.5rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    cursor: pointer;
}}
.vd-select:focus {{ outline: none; border-color: var(--vd-color-secondary); }}
.vd-option {{ color: var(--vd-color-text); background: var(--vd-color-surface); }}

/* Checkbox */
.vd-checkbox {{
    width: 1rem; height: 1rem; border: 1px solid var(--vd-color-border);
    border-radius: {r}sm); cursor: pointer; accent-color: var(--vd-color-secondary);
}}

/* Radio */
.vd-radio {{
    width: 1rem; height: 1rem; border: 1px solid var(--vd-color-border);
    border-radius: {r}full); cursor: pointer; accent-color: var(--vd-color-secondary);
}}

/* Heading */
.vd-heading {{
    color: var(--vd-color-text); font-weight: var(--vd-weight-bold);
    line-height: var(--vd-leading-tight); letter-spacing: -0.025em;
    text-wrap: balance;
}}
.vd-heading--h1 {{ font-size: {t}xxxl); font-weight: var(--vd-weight-bold); }}
.vd-heading--h2 {{ font-size: {t}xxl); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h3 {{ font-size: {t}xl); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h4 {{ font-size: {t}lg); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h5 {{ font-size: {t}md); font-weight: var(--vd-weight-medium); }}
.vd-heading--h6 {{ font-size: {t}sm); font-weight: var(--vd-weight-medium); }}

/* Badge */
.vd-badge {{
    display: inline-flex; align-items: center; border-radius: {r}full);
    padding: 0.125rem 0.625rem; font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    transition: background {m}normal);
}}
.vd-badge--default {{ background: var(--vd-color-text); color: var(--vd-color-surface); }}
.vd-badge--secondary {{
    background: var(--vd-color-surface); color: var(--vd-color-text);
    border: 1px solid var(--vd-color-border);
}}
.vd-badge--outline {{ color: var(--vd-color-text); border: 1px solid var(--vd-color-border); }}
.vd-badge--success {{ background: var(--vd-color-success); color: #fff; }}
.vd-badge--warning {{ background: var(--vd-color-warning); color: #000; }}
.vd-badge--danger {{ background: var(--vd-color-danger); color: #fff; }}

/* Avatar */
.vd-avatar {{
    position: relative; display: flex; height: 2.5rem; width: 2.5rem;
    overflow: hidden; border-radius: {r}full); flex-shrink: 0;
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
}}
.vd-avatar-img {{ height: 100%; width: 100%; object-fit: cover; }}
.vd-avatar-fallback {{
    display: flex; height: 100%; width: 100%; align-items: center;
    justify-content: center; border-radius: {r}full);
    background: var(--vd-color-surface);
    color: var(--vd-color-text); font-size: {t}sm); font-weight: var(--vd-weight-medium);
}}

/* Divider */
.vd-divider {{
    margin: 0; height: 1px; width: 100%; border: none;
    background: var(--vd-color-border);
}}

/* Dialog */
.vd-dialog {{
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    border-radius: {r}xl); box-shadow: {sh}lg); color: var(--vd-color-text);
}}
.vd-dialog::backdrop {{ background: rgb(0 0 0 / 0.5); }}

/* Modal */
.vd-modal {{
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    border-radius: {r}xl); box-shadow: {sh}lg);
    padding: {s}xl); width: 100%; max-width: 32rem;
    margin: auto; display: flex; flex-direction: column; gap: {s}md);
    color: var(--vd-color-text);
}}
.vd-modal::backdrop {{ background: rgb(0 0 0 / 0.6); }}

/* Link */
.vd-link {{
    color: var(--vd-color-secondary); text-decoration: none;
    text-underline-offset: 4px; cursor: pointer;
    transition: color {m}normal);
}}
.vd-link:hover {{ text-decoration: underline; }}

/* List */
.vd-list {{ list-style: none; padding-left: 0; margin: 0; }}
.vd-list--ordered {{ list-style: decimal; padding-left: 1.5rem; }}
.vd-list--unstyled {{ list-style: none; padding-left: 0; }}
.vd-list-item {{ padding: {s}xs) 0; color: var(--vd-color-text); }}

/* ChatBox */
.vd-chatbox {{
    display: flex; flex-direction: column; gap: {s}sm);
    overflow-y: auto;
}}

/* Icon (inline SVG sizing + alignment) */
.vd-icon {{
    display: inline-block; vertical-align: middle; flex-shrink: 0;
}}

/* Message list (chat transcript) */
.vd-message-list {{
    display: flex; flex-direction: column; gap: {s}md);
    overflow-y: auto; padding: {s}md);
    flex: 1; min-height: 0;
}}

/* Chat message bubbles */
.vd-chat-message {{
    display: flex; flex-direction: column; max-width: 80%;
    padding: {s}sm) {s}md); border-radius: {r}lg);
    font-size: {t}sm); line-height: 1.6; color: var(--vd-color-text);
    white-space: pre-wrap; word-break: break-word;
}}
.vd-chat-message--user {{
    align-self: flex-end;
    background: var(--vd-color-primary); color: var(--vd-color-primary-contrast, #fff);
    border-bottom-right-radius: {r}sm);
}}
.vd-chat-message--assistant {{
    align-self: flex-start;
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-bottom-left-radius: {r}sm);
}}
.vd-chat-message--system {{
    align-self: center; font-size: {t}xs); color: var(--vd-color-text-muted);
    background: transparent;
}}
.vd-chat-message--tool {{
    align-self: flex-start; font-size: {t}xs);
    background: var(--vd-color-surface); border: 1px dashed var(--vd-color-border);
    color: var(--vd-color-text-muted); font-family: var(--vd-font-mono, monospace);
}}
.vd-chat-message pre, .vd-chat-message code {{
    font-family: var(--vd-font-mono, monospace); font-size: {t}xs);
}}
.vd-chat-message pre {{
    background: rgb(0 0 0 / 0.25); padding: {s}sm); border-radius: {r}md);
    overflow-x: auto; white-space: pre; margin: {s}xs) 0;
}}

/* Streaming text + caret */
.vd-streaming-text {{
    white-space: pre-wrap; word-break: break-word; color: var(--vd-color-text);
}}
.vd-caret {{
    display: inline-block; width: 0.5em; height: 1em; margin-left: 2px;
    vertical-align: text-bottom; background: var(--vd-color-primary);
    animation: vd-blink 1s steps(2) infinite;
}}
@keyframes vd-blink {{ 50% {{ opacity: 0; }} }}

/* Composer (chat input bar) */
.vd-composer {{
    display: flex; align-items: flex-end; gap: {s}sm);
    padding: {s}sm); border: 1px solid var(--vd-color-border);
    border-radius: {r}lg); background: var(--vd-color-surface);
}}
.vd-composer-input {{
    flex: 1; resize: none; border: none; outline: none; background: transparent;
    color: var(--vd-color-text); font-size: {t}sm); line-height: 1.5;
    font-family: inherit; padding: {s}xs) {s}sm);
    max-height: 200px;
}}
.vd-composer-input:focus {{ box-shadow: none; }}
.vd-composer-send {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 2.25rem; height: 2.25rem; border: none; cursor: pointer;
    border-radius: {r}md); background: var(--vd-color-primary);
    color: var(--vd-color-primary-contrast, #fff);
    transition: opacity {m}normal);
}}
.vd-composer-send:hover {{ opacity: 0.9; }}
.vd-composer-send:disabled {{ opacity: 0.5; cursor: not-allowed; }}

/* Sidebar shell */
.vd-sidebar {{
    display: flex; flex-direction: column; gap: {s}sm);
    width: 16rem; padding: {s}md); flex-shrink: 0;
    border-right: 1px solid var(--vd-color-border);
    background: var(--vd-color-surface); color: var(--vd-color-text);
    overflow-y: auto;
}}
.vd-sidebar-heading {{
    font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    text-transform: uppercase; letter-spacing: 0.08em;
    color: var(--vd-color-text-muted); padding: 0 {s}xs);
}}

/* Markdown rendered inside components */
.vd-markdown p {{ margin: 0 0 {s}sm); }}
.vd-markdown p:last-child {{ margin-bottom: 0; }}
.vd-markdown h1, .vd-markdown h2, .vd-markdown h3,
.vd-markdown h4, .vd-markdown h5, .vd-markdown h6 {{
    margin: {s}sm) 0 {s}xs); font-weight: var(--vd-weight-semibold);
    color: var(--vd-color-text); line-height: 1.3;
}}
.vd-markdown ul, .vd-markdown ol {{ margin: 0 0 {s}sm); padding-left: 1.25rem; }}
.vd-markdown li {{ margin: {s}xs) 0; }}
.vd-markdown blockquote {{
    margin: 0 0 {s}sm); padding: {s}xs) {s}sm);
    border-left: 3px solid var(--vd-color-border);
    color: var(--vd-color-text-muted);
}}
.vd-markdown code {{
    font-family: var(--vd-font-mono, monospace); font-size: 0.875em;
    background: rgb(0 0 0 / 0.15); padding: 0.125em 0.375em; border-radius: {r}sm);
}}
.vd-markdown pre {{
    margin: 0 0 {s}sm); padding: {s}sm); overflow-x: auto;
    background: rgb(0 0 0 / 0.25); border-radius: {r}md);
}}
.vd-markdown pre code {{ background: transparent; padding: 0; }}
.vd-markdown a {{
    color: var(--vd-color-secondary); text-underline-offset: 4px;
}}

/* Semantic structure */
.vd-nav {{
    display: flex; align-items: center; gap: {s}md);
    padding: {s}md) {s}lg); border-bottom: 1px solid var(--vd-color-border);
    background: var(--vd-color-background);
}}
.vd-header {{
    display: flex; align-items: center; justify-content: space-between;
    padding: {s}md) {s}lg); border-bottom: 1px solid var(--vd-color-border);
    background: var(--vd-color-background);
}}
.vd-footer {{
    padding: {s}lg); border-top: 1px solid var(--vd-color-border);
    color: var(--vd-color-text-muted); font-size: {t}sm);
    background: var(--vd-color-background);
}}
.vd-main {{ flex: 1; }}
.vd-section {{ padding: {s}xl) 0; }}
.vd-article {{ max-width: 65ch; }}
.vd-aside {{ color: var(--vd-color-text-muted); font-size: {t}sm); }}
.vd-figure {{ margin: 0; }}
.vd-figcaption {{
    font-size: {t}sm); color: var(--vd-color-text-muted); margin-top: {s}sm);
}}
.vd-address {{ font-style: normal; color: var(--vd-color-text-muted); }}
.vd-time {{ color: var(--vd-color-text-muted); font-size: {t}sm); }}
.vd-img {{ border-radius: {r}md); }}

/* Table */
.vd-table {{ width: 100%; border-collapse: collapse; color: var(--vd-color-text); }}
.vd-table-head {{
    background: var(--vd-color-surface); border-bottom: 1px solid var(--vd-color-border);
}}
.vd-table-row {{
    border-bottom: 1px solid var(--vd-color-border);
    transition: background {m}normal);
}}
.vd-table-row:hover {{ background: var(--vd-color-surface); }}
.vd-table-header-cell {{
    padding: 0.875rem 1.5rem; text-align: left;
    font-size: {t}xs); font-weight: var(--vd-weight-medium);
    color: var(--vd-color-text-muted); text-transform: uppercase;
    letter-spacing: 0.05em;
}}
.vd-table-cell {{
    padding: 0.875rem 1.5rem; white-space: nowrap;
    font-size: {t}sm); color: var(--vd-color-text);
}}

/* User badge */
.vd-user-badge {{
    display: inline-flex; align-items: center; gap: {s}sm);
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-radius: {r}full); padding: 0.25rem 0.75rem 0.25rem 0.25rem;
    color: var(--vd-color-text); font-size: {t}sm); font-weight: var(--vd-weight-medium);
}}
.vd-user-badge-avatar {{
    display: flex; height: 1.75rem; width: 1.75rem; align-items: center;
    justify-content: center; border-radius: {r}full);
    background: var(--vd-color-secondary); color: #fff;
    font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    text-transform: uppercase;
}}
.vd-user-badge-name {{ line-height: 1; font-size: {t}sm); }}
.vd-user-badge-meta {{ font-size: {t}xs); color: var(--vd-color-text-muted); }}

/* Auth guard */
.vd-auth-guard {{
    padding: {s}md); text-align: center; font-size: {t}sm);
    color: var(--vd-color-text-muted);
}}
.vd-auth-guard--error {{ color: var(--vd-color-danger); font-weight: var(--vd-weight-medium); }}

/* Chrome — navbar */
.vd-navbar {{
    position: sticky; top: 0; z-index: 40;
    display: flex; align-items: center; justify-content: space-between;
    flex-wrap: wrap; gap: {s}sm) {s}md);
    padding: {s}md) {s}lg);
    background: color-mix(in srgb, var(--vd-color-background) 82%, transparent);
    backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid var(--vd-color-border-soft);
}}
.vd-navbar--sticky {{ position: sticky; top: 0; }}

/* Chrome — nav link */
.vd-nav-link {{
    color: var(--vd-color-text-muted); text-decoration: none;
    font-size: {t}sm); font-weight: var(--vd-weight-medium);
    padding: 0.375rem 0.625rem; border-radius: {r}md);
    transition: color {m}normal), background {m}normal);
}}
.vd-nav-link:hover {{ color: var(--vd-color-text); background: var(--vd-color-surface); }}
.vd-nav-link--active {{ color: var(--vd-color-primary); }}

/* Chrome — brand */
.vd-brand {{
    font-family: var(--vd-font-display);
    font-size: {t}lg); font-weight: var(--vd-weight-bold);
    color: var(--vd-color-text); text-decoration: none; letter-spacing: -0.02em;
}}

/* Chrome — theme toggle */
.vd-theme-toggle {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 2.25rem; height: 2.25rem; border-radius: {r}full);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    color: var(--vd-color-text); cursor: pointer; font-size: {t}sm);
    transition: background {m}normal), border-color {m}normal);
}}
.vd-theme-toggle:hover {{ background: var(--vd-color-surface-raised); }}
.vd-theme-toggle-sun {{ display: none; }}
.vd-theme-toggle-moon {{ display: inline; }}
.dark .vd-theme-toggle-sun {{ display: inline; }}
.dark .vd-theme-toggle-moon {{ display: none; }}

/* Chrome — eyebrow */
.vd-eyebrow {{
    display: inline-block; font-size: {t}xs);
    font-weight: var(--vd-weight-semibold); letter-spacing: 0.12em;
    text-transform: uppercase; color: var(--vd-color-secondary);
}}

/* Chrome — hero */
.vd-hero {{
    display: grid; gap: {s}xl);
    padding: {s}xxl) 0;
}}

/* Chrome — page hero */
.vd-page-hero {{
    padding: {s}xxl) {s}lg);
    border-bottom: 1px solid var(--vd-color-border);
    background: var(--vd-color-surface);
}}

/* Chrome — chip */
.vd-chip {{
    display: inline-flex; align-items: center; gap: 0.375rem;
    padding: 0.25rem 0.75rem; border-radius: {r}full);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    font-size: {t}xs); font-weight: var(--vd-weight-medium);
    color: var(--vd-color-text-muted);
}}

/* Chrome — code block */
.vd-code-block {{
    background: var(--vd-code-background);
    border: 1px solid var(--vd-code-border);
    border-radius: {r}lg); padding: {s}lg);
    overflow-x: auto; white-space: pre;
    font-family: var(--vd-font-mono);
    font-size: {t}sm); line-height: 1.7; color: var(--vd-code-text);
}}
.vd-code-block code {{ font: inherit; color: inherit; }}

/* Chrome — stats */
.vd-stats {{ display: grid; gap: {s}md); }}
.vd-stats--cols-2 {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
.vd-stats--cols-3 {{ grid-template-columns: repeat(3, minmax(0, 1fr)); }}
.vd-stats--cols-4 {{ grid-template-columns: repeat(4, minmax(0, 1fr)); }}
.vd-stat {{
    display: flex; flex-direction: column; gap: {s}xs);
    padding: {s}lg); border-radius: {r}lg);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
}}
.vd-stat-value {{
    font-family: var(--vd-font-display);
    font-size: {t}xxxl); font-weight: var(--vd-weight-bold);
    color: var(--vd-color-text); letter-spacing: -0.02em;
}}
.vd-stat-label {{ font-size: {t}sm); color: var(--vd-color-text-muted); }}

/* Chrome — CTA band */
.vd-cta-band {{
    padding: {s}xxl) {s}lg); text-align: center;
    background: var(--vd-color-secondary-soft);
    border-top: 1px solid var(--vd-color-secondary-line);
    border-bottom: 1px solid var(--vd-color-secondary-line);
}}

/* Chrome — back link */
.vd-back-link {{
    display: inline-flex; align-items: center; gap: 0.375rem;
    color: var(--vd-color-text-muted); text-decoration: none;
    font-size: {t}sm); font-weight: var(--vd-weight-medium);
    transition: color {m}normal);
}}
.vd-back-link::before {{ content: "\\2190"; }}
.vd-back-link:hover {{ color: var(--vd-color-text); }}

/* Chrome — feature card */
.vd-feature-card {{
    padding: {s}lg); border-radius: {r}xl);
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    transition: transform {m}normal), border-color {m}normal), box-shadow {m}normal);
}}
.vd-feature-card:hover {{
    transform: translateY(-2px);
    border-color: var(--vd-color-secondary);
    box-shadow: {sh}lg);
}}

/* Chrome — link arrow */
.vd-link-arrow {{
    display: inline-flex; align-items: center; gap: 0.375rem;
    color: var(--vd-color-secondary); text-decoration: none;
    font-weight: var(--vd-weight-medium); font-size: {t}sm);
}}
.vd-link-arrow::after {{ content: "\\2192"; transition: transform {m}fast); }}
.vd-link-arrow:hover::after {{ transform: translateX(2px); }}

/* Motion */
@keyframes vd-fade-up {{
    from {{ opacity: 0; transform: translateY(12px); }}
    to {{ opacity: 1; transform: translateY(0); }}
}}
@keyframes vd-fade-in {{
    from {{ opacity: 0; }}
    to {{ opacity: 1; }}
}}
@keyframes vd-pulse {{
    0%, 100% {{ opacity: 1; }}
    50% {{ opacity: 0.6; }}
}}
.vd-hero, .vd-page-hero, .vd-cta-band {{
    animation: vd-fade-up {m}slow) ease-out both;
}}

/* Responsive chrome */
@media (max-width: 767px) {{
    .vd-stats--cols-2, .vd-stats--cols-3, .vd-stats--cols-4 {{
        grid-template-columns: 1fr;
    }}
    .vd-navbar {{ justify-content: center; }}
}}

/* Respect reduced-motion preferences */
@media (prefers-reduced-motion: reduce) {{
    *, *::before, *::after {{
        animation: none !important;
        transition: none !important;
    }}
}}
""" + _layout_css()


def _layout_css() -> str:
    """Generate the flex/grid/container/page modifier rules."""
    css: list[str] = []

    # Flex
    css.append("/* Flex */")
    css.append(".vd-flex { display: flex; }")
    css.append(".vd-flex--row { flex-direction: row; }")
    css.append(".vd-flex--col { flex-direction: column; }")
    css.append(".vd-flex--row-reverse { flex-direction: row-reverse; }")
    css.append(".vd-flex--col-reverse { flex-direction: column-reverse; }")
    justify = {
        "start": "flex-start",
        "end": "flex-end",
        "center": "center",
        "between": "space-between",
        "around": "space-around",
        "evenly": "space-evenly",
    }
    for name, value in justify.items():
        css.append(f".vd-flex--justify-{name} {{ justify-content: {value}; }}")
    items = {
        "start": "flex-start",
        "end": "flex-end",
        "center": "center",
        "baseline": "baseline",
        "stretch": "stretch",
    }
    for name, value in items.items():
        css.append(f".vd-flex--items-{name} {{ align-items: {value}; }}")
    css.append(".vd-flex--nowrap { flex-wrap: nowrap; }")
    css.append(".vd-flex--wrap { flex-wrap: wrap; }")
    css.append(".vd-flex--wrap-reverse { flex-wrap: wrap-reverse; }")

    # Grid
    css.append("/* Grid */")
    css.append(".vd-grid { display: grid; }")
    for n in range(1, 13):
        css.append(
            f".vd-grid--cols-{n} {{ grid-template-columns: repeat({n}, minmax(0, 1fr)); }}"
        )

    # Gap utilities (shared by flex + grid)
    css.append("/* Gap */")
    for g in _GAP_SCALE:
        if g == "0":
            value = "0"
        elif g.isdigit():
            # Numeric gaps follow Tailwind's 4px base: gap-4 == 1rem.
            value = f"calc(0.25rem * {g})"
        else:
            value = f"var(--vd-space-{g})"
        css.append(f".vd-flex--gap-{g} {{ gap: {value}; }}")
        css.append(f".vd-grid--gap-{g} {{ gap: {value}; }}")

    # Container
    css.append("/* Container */")
    css.append(".vd-container { width: 100%; margin-left: auto; margin-right: auto; }")
    css.append(".vd-container--centered { margin-left: auto; margin-right: auto; }")
    for name, value in _CONTAINER_SIZES.items():
        css.append(f".vd-container--{name} {{ max-width: {value}; }}")

    # Page
    css.append("/* Page */")
    css.append(
        ".vd-page { width: 100%; flex: 1; margin-left: auto; margin-right: auto; }"
    )
    css.append(".vd-page--pad { padding: var(--vd-space-xl) var(--vd-space-md); }")
    for name, value in _CONTAINER_SIZES.items():
        css.append(f".vd-page--{name} {{ max-width: {value}; }}")

    return "\n".join(css) + "\n"
