"""The native Voodoo CSS adapter.

Returns semantic class names (``vd-button``, ``vd-button--primary``). The
matching CSS is generated by :func:`generate_component_css` and included in
``render_page``. All values reference ``--vd-*`` tokens, so changing the
theme at runtime changes every component without re-rendering.

This is the default adapter. Tailwind is opt-in::

    from voodoo import TailwindAdapter, set_style_adapter
    set_style_adapter(TailwindAdapter())
"""

from __future__ import annotations

from typing import Any

from voodoo.ui.styles.theme import Theme


class VoodooCSSAdapter:
    """Returns semantic ``vd-*`` class names resolved by generated CSS."""

    def component_classes(
        self, component: str, props: dict[str, Any], theme: Theme
    ) -> str:
        # Build BEM-style class names from the semantic key + props
        base = component.replace(".", "-")
        classes: list[str] = [f"vd-{base}"]

        variant = props.get("variant")
        if variant:
            classes.append(f"vd-{base}--{variant}")

        size = props.get("size")
        if size and size != "md":
            classes.append(f"vd-{base}--{size}")

        # Heading level
        level = props.get("level")
        if level and component == "heading":
            classes.append(f"vd-{base}--h{level}")

        return " ".join(classes)


# ---------------------------------------------------------------------------
# CSS generation — produces the stylesheet for all vd-* classes
# ---------------------------------------------------------------------------


def generate_component_css(theme: Theme) -> str:
    """Generate CSS for all ``vd-*`` component classes.

    Uses ``--vd-*`` tokens exclusively so theme changes propagate instantly.
    """
    r = "var(--vd-radius-"
    s = "var(--vd-space-"
    t = "var(--vd-text-"
    sh = "var(--vd-shadow-"
    m = "var(--vd-motion-"

    return f"""
/* ── Voodoo Component CSS (generated) ─────────────────────────────── */

/* Button */
.vd-button {{
    display: inline-flex; align-items: center; justify-content: center;
    gap: {s}sm); white-space: nowrap;
    border-radius: {r}md); font-size: {t}sm); font-weight: var(--vd-weight-medium);
    transition: background {m}normal), color {m}normal), border-color {m}normal);
    border: none; cursor: pointer; outline: none;
    height: 2.25rem; padding: 0 1rem;
}}
.vd-button:focus-visible {{ box-shadow: 0 0 0 2px var(--vd-color-primary); }}
.vd-button:disabled {{ pointer-events: none; opacity: 0.5; }}
.vd-button--primary {{
    background: var(--vd-color-primary); color: #fff;
}}
.vd-button--primary:hover {{ background: var(--vd-color-primary-hover); }}
.vd-button--secondary {{
    background: var(--vd-color-secondary); color: #fff;
}}
.vd-button--secondary:hover {{ opacity: 0.9; }}
.vd-button--outline {{
    border: 1px solid var(--vd-color-border); background: transparent;
    color: var(--vd-color-text);
}}
.vd-button--outline:hover {{ background: var(--vd-color-surface); }}
.vd-button--ghost {{
    background: transparent; color: var(--vd-color-text-muted);
}}
.vd-button--ghost:hover {{
    background: var(--vd-color-surface); color: var(--vd-color-text);
}}
.vd-button--danger {{
    background: var(--vd-color-danger); color: #fff;
}}
.vd-button--danger:hover {{ opacity: 0.9; }}
.vd-button--sm {{ height: 2rem; padding: 0 0.75rem; font-size: {t}xs); }}
.vd-button--lg {{ height: 2.5rem; padding: 0 1.5rem; font-size: {t}md); }}

/* Card */
.vd-card {{
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    border-radius: {r}xl); padding: {s}xl);
    box-shadow: {sh}sm);
}}

/* Input */
.vd-input {{
    display: flex; width: 100%; height: 2.25rem;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.25rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    transition: border-color {m}normal), box-shadow {m}normal);
}}
.vd-input::placeholder {{ color: var(--vd-color-text-muted); }}
.vd-input:focus-visible {{
    outline: none; border-color: var(--vd-color-primary);
    box-shadow: 0 0 0 1px var(--vd-color-primary);
}}
.vd-input:disabled {{ opacity: 0.5; cursor: not-allowed; }}
.vd-input--sm {{ height: 2rem; padding: 0.25rem 0.625rem; }}
.vd-input--lg {{ height: 2.75rem; padding: 0.5rem 1rem; }}

/* Textarea */
.vd-textarea {{
    display: flex; min-height: 80px; width: 100%;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.5rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    transition: border-color {m}normal);
}}
.vd-textarea:focus-visible {{
    outline: none; border-color: var(--vd-color-primary);
    box-shadow: 0 0 0 1px var(--vd-color-primary);
}}

/* Select */
.vd-select {{
    display: flex; width: 100%; height: 2.25rem; align-items: center;
    border: 1px solid var(--vd-color-border); background: transparent;
    border-radius: {r}md); padding: 0.5rem 0.75rem;
    font-size: {t}sm); color: var(--vd-color-text);
    cursor: pointer;
}}
.vd-select:focus {{ outline: none; border-color: var(--vd-color-primary); }}

/* Label */
.vd-label {{
    display: block; font-size: {t}sm); font-weight: var(--vd-weight-medium);
    line-height: 1; color: var(--vd-color-text);
}}

/* Checkbox */
.vd-checkbox {{
    width: 1rem; height: 1rem; border: 1px solid var(--vd-color-border);
    border-radius: {r}sm); cursor: pointer; accent-color: var(--vd-color-primary);
}}

/* Radio */
.vd-radio {{
    width: 1rem; height: 1rem; border: 1px solid var(--vd-color-border);
    border-radius: {r}full); cursor: pointer; accent-color: var(--vd-color-primary);
}}

/* Heading */
.vd-heading {{
    color: var(--vd-color-text); font-weight: var(--vd-weight-bold);
    line-height: var(--vd-leading-tight);
}}
.vd-heading--h1 {{ font-size: {t}xxxl); font-weight: var(--vd-weight-bold); }}
.vd-heading--h2 {{ font-size: {t}xxl); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h3 {{ font-size: {t}xl); font-weight: var(--vd-weight-semibold); }}
.vd-heading--h4 {{ font-size: {t}lg); font-weight: var(--vd-weight-semibold); }}

/* Badge */
.vd-badge {{
    display: inline-flex; align-items: center; border-radius: {r}full);
    padding: 0.125rem 0.625rem; font-size: {t}xs); font-weight: var(--vd-weight-semibold);
    transition: background {m}normal);
}}
.vd-badge--default {{ background: var(--vd-color-text); color: var(--vd-color-surface); }}
.vd-badge--secondary {{
    background: var(--vd-color-surface); color: var(--vd-color-text);
    border: 1px solid var(--vd-color-border);
}}
.vd-badge--outline {{ color: var(--vd-color-text); border: 1px solid var(--vd-color-border); }}
.vd-badge--success {{ background: var(--vd-color-success); color: #fff; }}
.vd-badge--warning {{ background: var(--vd-color-warning); color: #000; }}
.vd-badge--danger {{ background: var(--vd-color-danger); color: #fff; }}

/* Avatar */
.vd-avatar {{
    position: relative; display: flex; height: 2.5rem; width: 2.5rem;
    overflow: hidden; border-radius: {r}full); flex-shrink: 0;
}}
.vd-avatar-img {{ height: 100%; width: 100%; object-fit: cover; }}
.vd-avatar-fallback {{
    display: flex; height: 100%; width: 100%; align-items: center;
    justify-content: center; border-radius: {r}full);
    background: var(--vd-color-surface); border: 1px solid var(--vd-color-border);
    color: var(--vd-color-text); font-size: {t}sm); font-weight: var(--vd-weight-medium);
}}

/* Divider */
.vd-divider {{
    margin: 0; height: 1px; width: 100%; border: none;
    background: var(--vd-color-border);
}}

/* Dialog */
.vd-dialog {{
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    border-radius: {r}xl); box-shadow: {sh}lg);
}}
.vd-dialog::backdrop {{ background: rgb(0 0 0 / 0.5); }}

/* Modal */
.vd-modal {{
    border: 1px solid var(--vd-color-border); background: var(--vd-color-surface);
    border-radius: {r}xl); box-shadow: {sh}lg);
    padding: {s}xl); width: 100%; max-width: 32rem;
    margin: auto; display: flex; flex-direction: column; gap: {s}md);
    color: var(--vd-color-text);
}}
.vd-modal::backdrop {{ background: rgb(0 0 0 / 0.6); }}

/* Link */
.vd-link {{
    color: var(--vd-color-primary); text-decoration: none;
    text-underline-offset: 4px; cursor: pointer;
    transition: color {m}normal);
}}
.vd-link:hover {{ text-decoration: underline; }}

/* List */
.vd-list {{ list-style: disc; padding-left: 1.5rem; }}
.vd-list--ordered {{ list-style: decimal; }}
.vd-list--unstyled {{ list-style: none; padding-left: 0; }}

/* ChatBox */
.vd-chatbox {{
    display: flex; flex-direction: column; gap: {s}sm);
    overflow-y: auto;
}}

/* Flex */
.vd-flex {{ display: flex; }}
.vd-flex--row {{ flex-direction: row; }}
.vd-flex--col {{ flex-direction: column; }}
.vd-flex--row-reverse {{ flex-direction: row-reverse; }}
.vd-flex--col-reverse {{ flex-direction: column-reverse; }}

/* Grid */
.vd-grid {{ display: grid; gap: {s}md); }}

/* Container */
.vd-container {{ max-width: 80rem; margin-left: auto; margin-right: auto; }}

/* Page */
.vd-page {{
    max-width: 64rem; margin-left: auto; margin-right: auto;
    width: 100%; flex: 1; padding: {s}xl) {s}md);
}}

/* Table */
.vd-table-head {{
    background: var(--vd-color-surface); border-bottom: 1px solid var(--vd-color-border);
}}
.vd-table-row {{
    border-bottom: 1px solid var(--vd-color-border);
    transition: background {m}normal);
}}
.vd-table-row:hover {{ background: var(--vd-color-surface); }}
.vd-table-header-cell {{
    padding: 0.875rem 1.5rem; text-align: left;
    font-size: {t}xs); font-weight: var(--vd-weight-medium);
    color: var(--vd-color-text-muted); text-transform: uppercase;
    letter-spacing: 0.05em;
}}
.vd-table-cell {{
    padding: 0.875rem 1.5rem; white-space: nowrap;
    font-size: {t}sm); color: var(--vd-color-text);
}}
"""
