"""Model facade — async CRUD on top of :class:`BaseModel`.

``Model`` adds a small, ergonomic async CRUD API (``create``, ``get``,
``all``, ``save``, ``delete``) while reusing the existing aiosqlite
storage layer and the ``on_insert`` / ``on_update`` hook system from
:mod:`voodoo.data.base`.

Storage backend boundary
-------------------------
Everything in this module talks to the database through ``get_db()``
and builds portable ANSI-SQL strings.  Swapping SQLite for PostgreSQL
(or another backend) only requires replacing the connection function
and the DDL generated by ``BaseModel._create_table``; the facade stays
the same.  Migrations are an explicit extension point: today the only
DDL emitted is ``CREATE TABLE IF NOT EXISTS`` (create-if-absent).  A
future migration runner can hook into ``init_db`` without changing any
call-site here.
"""

from typing import Any, get_type_hints

from voodoo.data.base import BaseModel, _get_table_name, get_db

__all__ = ["Model"]


class Model(BaseModel):
    """Async CRUD facade over :class:`voodoo.data.BaseModel`.

    Subclass it just like ``BaseModel`` and use the async helpers::

        class Lead(Model):
            name: str
            email: str

        lead = await Lead.create(name="Ada", email="ada@x.io")
        lead = await Lead.get(lead.id)
        leads = await Lead.all()
        lead.email = "ada@y.io"
        await lead.save()
        await lead.delete()
    """

    # ------------------------------------------------------------------
    # Class-level CRUD
    # ------------------------------------------------------------------

    @classmethod
    async def create(cls, **kwargs: Any) -> "Model":
        """Instantiate, insert, and return the new row as a model instance."""
        obj = cls()
        for key, value in kwargs.items():
            setattr(obj, key, value)
        await obj.insert()
        return obj

    @classmethod
    async def get(cls, id: int) -> "Model | None":
        """Fetch a single row by primary key; ``None`` if not found."""
        from voodoo.telemetry import telemetry_store

        telemetry_store.record_db_query()
        db = await get_db()
        table_name = _get_table_name(cls)
        query = f"SELECT * FROM {table_name} WHERE id = ?"
        async with db.execute(query, (id,)) as cursor:
            row = await cursor.fetchone()

        if row is None:
            return None

        obj = cls()
        hints = get_type_hints(cls)
        for key in row.keys():
            val = row[key]
            if key in hints and hints[key] is bool:
                val = bool(val)
            setattr(obj, key, val)
        return obj

    @classmethod
    async def all(cls, user_context: dict | None = None) -> list["Model"]:
        """Return every row as model instances (alias of ``find_all``)."""
        return await cls.find_all(user_context=user_context)

    # ------------------------------------------------------------------
    # Instance-level CRUD
    # ------------------------------------------------------------------

    async def save(self) -> "Model":
        """Insert if the instance has no ``id`` yet, otherwise update."""
        if not getattr(self, "id", None):
            await self.insert()
        else:
            await self.update()
        return self

    async def delete(self) -> None:
        """Delete the row represented by this instance."""
        from voodoo.telemetry import telemetry_store

        telemetry_store.record_db_query()
        db = await get_db()
        table_name = _get_table_name(self)
        await db.execute(f"DELETE FROM {table_name} WHERE id = ?", (self.id,))
        await db.commit()
