from .core import create_app, register_event, ws_manager
from .components import (
    Component,
    Div,
    Flex,
    Grid,
    Container,
    A,
    Button,
    Card,
    Text,
    Heading,
    Badge,
    Avatar,
    Divider,
    Dialog,
    List,
    ListItem,
    Form,
    Label,
    Input,
    Textarea,
    Select,
    Option,
    Checkbox,
    Radio,
    ChatBox,
    Table,
    # Semantic HTML (SEO & Accessibility)
    Nav,
    Header,
    Footer,
    Main,
    Section,
    Article,
    Aside,
    Figure,
    FigCaption,
    Time,
    Address,
    Img,
    Paragraph,
    # Auth & Security Components
    LoginForm,
    RegisterForm,
    UserBadge,
    AuthGuard,
)
from .data import BaseModel, on_insert, on_update, rls_policy, get_db
from .queue import queue, enqueue
from .agent import Agent
from .api import api
from .storage import storage
from .mcp import mcp, MCPClient
from .mesh import mesh
from .status import ServiceStatus
from .telemetry import trace, TelemetryMiddleware, telemetry_store
from .config import config, SEOConfig, AuthConfig, SecurityConfig
from .theme import Theme, ThemeColors, set_theme, default_theme
from .i18n import _, I18n, i18n_instance
from .seo import SEO, OpenGraph, TwitterCard, GEO, FAQ
from .auth import (
    hash_password,
    verify_password,
    create_access_token,
    decode_access_token,
    generate_api_key,
    hash_api_key,
    verify_api_key,
    generate_secret_key,
    AuthUser,
    User,
    get_current_user,
    current_user,
    set_auth_cookie,
    clear_auth_cookie,
    require_auth,
    require_roles,
    require_scopes,
    require_api_key,
    login_required,
    requires_role,
    requires_roles,
    requires_permission,
    requires_scopes,
    requires_api_key,
    AuthMiddleware,
    AuthError,
    InvalidCredentialsError,
    ExpiredTokenError,
    InvalidTokenError,
    PermissionDeniedError,
)
from .security import (
    SecurityHeadersMiddleware,
    CORSMiddleware,
    CSRFMiddleware,
    RateLimitMiddleware,
    RateLimiter,
    rate_limiter,
    generate_csrf_token,
    set_csrf_cookie,
    validate_password_strength,
)

__all__ = [
    "create_app",
    "register_event",
    "ws_manager",
    "Component",
    "Div",
    "Flex",
    "Grid",
    "Container",
    "A",
    "Button",
    "Card",
    "Text",
    "Heading",
    "Badge",
    "Avatar",
    "Divider",
    "Dialog",
    "List",
    "ListItem",
    "Form",
    "Label",
    "Input",
    "Textarea",
    "Select",
    "Option",
    "Checkbox",
    "Radio",
    "ChatBox",
    "Table",
    # Semantic HTML
    "Nav",
    "Header",
    "Footer",
    "Main",
    "Section",
    "Article",
    "Aside",
    "Figure",
    "FigCaption",
    "Time",
    "Address",
    "Img",
    "Paragraph",
    # Auth Components
    "LoginForm",
    "RegisterForm",
    "UserBadge",
    "AuthGuard",
    # Data
    "BaseModel",
    "on_insert",
    "on_update",
    "rls_policy",
    "get_db",
    "queue",
    "enqueue",
    "Agent",
    "api",
    "storage",
    "mcp",
    "MCPClient",
    "ServiceStatus",
    "trace",
    "TelemetryMiddleware",
    "telemetry_store",
    "config",
    "SEOConfig",
    "AuthConfig",
    "SecurityConfig",
    "Theme",
    "ThemeColors",
    "set_theme",
    "default_theme",
    "_",
    "I18n",
    "i18n_instance",
    "mesh",
    # SEO & GEO
    "SEO",
    "OpenGraph",
    "TwitterCard",
    "GEO",
    "FAQ",
    # Auth & Security
    "hash_password",
    "verify_password",
    "create_access_token",
    "decode_access_token",
    "generate_api_key",
    "hash_api_key",
    "verify_api_key",
    "generate_secret_key",
    "AuthUser",
    "User",
    "get_current_user",
    "current_user",
    "set_auth_cookie",
    "clear_auth_cookie",
    "require_auth",
    "require_roles",
    "require_scopes",
    "require_api_key",
    "login_required",
    "requires_role",
    "requires_roles",
    "requires_permission",
    "requires_scopes",
    "requires_api_key",
    "AuthMiddleware",
    "AuthError",
    "InvalidCredentialsError",
    "ExpiredTokenError",
    "InvalidTokenError",
    "PermissionDeniedError",
    "SecurityHeadersMiddleware",
    "CORSMiddleware",
    "CSRFMiddleware",
    "RateLimitMiddleware",
    "RateLimiter",
    "rate_limiter",
    "generate_csrf_token",
    "set_csrf_cookie",
    "validate_password_strength",
]

__version__ = "1.0.20"
