"""Compatibility shim — the component library lives in :mod:`voodoo.ui`.

``voodoo.components`` remains importable for existing apps and docs; new
code should import from ``voodoo.ui`` or the ``voodoo`` top level. Rendering
and styling now flow through the component base in :mod:`voodoo.ui.component`
and the active style adapter (see :mod:`voodoo.adapters.tailwind`).
"""

from voodoo.ui.library import (
    A,
    Address,
    Article,
    Aside,
    AuthGuard,
    Avatar,
    Badge,
    Button,
    Card,
    ChatBox,
    Checkbox,
    Component,
    Container,
    Dialog,
    Div,
    Divider,
    FigCaption,
    Figure,
    Flex,
    Footer,
    Form,
    Grid,
    Header,
    Heading,
    Img,
    Input,
    Label,
    List,
    ListItem,
    LoginForm,
    Main,
    Modal,
    Nav,
    Option,
    Page,
    Paragraph,
    Radio,
    RegisterForm,
    Section,
    Select,
    Table,
    Text,
    Textarea,
    Time,
    UserBadge,
)

__all__ = [
    "A",
    "Address",
    "Article",
    "Aside",
    "AuthGuard",
    "Avatar",
    "Badge",
    "Button",
    "Card",
    "ChatBox",
    "Checkbox",
    "Component",
    "Container",
    "Dialog",
    "Div",
    "Divider",
    "FigCaption",
    "Figure",
    "Flex",
    "Footer",
    "Form",
    "Grid",
    "Header",
    "Heading",
    "Img",
    "Input",
    "Label",
    "List",
    "ListItem",
    "LoginForm",
    "Main",
    "Modal",
    "Nav",
    "Option",
    "Page",
    "Paragraph",
    "Radio",
    "RegisterForm",
    "Section",
    "Select",
    "Table",
    "Text",
    "Textarea",
    "Time",
    "UserBadge",
]
